goog.module('org.patternfly.component.jumplinks.JumpLinks');

goog.require('elemental2.dom.DomGlobal.$Overlay');
goog.require('elemental2.dom.Event.$Overlay');
goog.require('elemental2.dom.HTMLDivElement.$Overlay');
goog.require('elemental2.dom.HTMLElement.$Overlay');
goog.require('elemental2.dom.HTMLUListElement.$Overlay');
goog.require('elemental2.dom.MouseEvent.$Overlay');
goog.require('elemental2.dom.MutationRecord.$Overlay');
goog.require('java.lang.Iterable');
goog.require('java.lang.String');
goog.require('java.util.HashMap');
goog.require('java.util.Map');
goog.require('java.util.function.Function');
goog.require('java.util.function.Supplier');
goog.require('nativebootstrap.Equality');
goog.require('nativebootstrap.Util');
goog.require('org.jboss.elemento.Attachable');
goog.require('org.jboss.elemento.By');
goog.require('org.jboss.elemento.Elements');
goog.require('org.jboss.elemento.EventType');
goog.require('org.jboss.elemento.HTMLContainerBuilder');
goog.require('org.patternfly.component.BaseComponentFlat');
goog.require('org.patternfly.component.ComponentType');
goog.require('org.patternfly.component.Expandable');
goog.require('org.patternfly.component.button.Button');
goog.require('org.patternfly.component.jumplinks.JumpLinksItem');
goog.require('org.patternfly.core.Aria');
goog.require('org.patternfly.core.Attributes');
goog.require('org.patternfly.core.Logger');
goog.require('org.patternfly.handler.SelectHandler');
goog.require('org.patternfly.handler.ToggleHandler');
goog.require('org.patternfly.icon.IconSets.fas');
goog.require('org.patternfly.style.Breakpoints');
goog.require('org.patternfly.style.Classes');
goog.require('org.patternfly.style.ExpandableModifier');
goog.require('org.patternfly.style.Modifiers');
goog.require('org.patternfly.style.Modifiers.Vertical');
goog.require('vmbootstrap.Arrays');
goog.require('vmbootstrap.Casts');

const JumpLinks = goog.require('org.patternfly.component.jumplinks.JumpLinks$impl');
exports = JumpLinks;
