goog.module('org.patternfly.component.tabs.Tab');

goog.require('elemental2.dom.DomGlobal.$Overlay');
goog.require('elemental2.dom.Element.$Overlay');
goog.require('elemental2.dom.Event.$Overlay');
goog.require('elemental2.dom.HTMLAnchorElement.$Overlay');
goog.require('elemental2.dom.HTMLButtonElement.$Overlay');
goog.require('elemental2.dom.HTMLElement.$Overlay');
goog.require('elemental2.dom.HTMLLIElement.$Overlay');
goog.require('elemental2.dom.MouseEvent.$Overlay');
goog.require('elemental2.promise.Promise.$Overlay');
goog.require('java.lang.String');
goog.require('java.util.function.Function');
goog.require('nativebootstrap.Equality');
goog.require('nativebootstrap.Util');
goog.require('org.jboss.elemento.Elements');
goog.require('org.jboss.elemento.EventType');
goog.require('org.jboss.elemento.HTMLContainerBuilder');
goog.require('org.jboss.elemento.Id');
goog.require('org.patternfly.component.Closeable');
goog.require('org.patternfly.component.ComponentType');
goog.require('org.patternfly.component.WithIcon');
goog.require('org.patternfly.component.WithText');
goog.require('org.patternfly.component.button.Button');
goog.require('org.patternfly.component.popover.Popover');
goog.require('org.patternfly.component.spinner.Spinner');
goog.require('org.patternfly.component.tabs.TabContent');
goog.require('org.patternfly.component.tabs.TabSubComponent');
goog.require('org.patternfly.component.tabs.Tabs');
goog.require('org.patternfly.component.tooltip.Tooltip');
goog.require('org.patternfly.core.Aria');
goog.require('org.patternfly.core.Attributes');
goog.require('org.patternfly.core.Logger');
goog.require('org.patternfly.handler.CloseHandler');
goog.require('org.patternfly.icon.IconSets.fas');
goog.require('org.patternfly.icon.IconSets.patternfly');
goog.require('org.patternfly.icon.PredefinedIcon');
goog.require('org.patternfly.style.Classes');
goog.require('org.patternfly.style.Modifiers');
goog.require('org.patternfly.style.Modifiers.Disabled');
goog.require('org.patternfly.style.Size');
goog.require('vmbootstrap.Arrays');
goog.require('vmbootstrap.Casts');

const Tab = goog.require('org.patternfly.component.tabs.Tab$impl');
exports = Tab;
