goog.module('org.patternfly.popper.PopperBuilder');

goog.require('elemental2.core.JsArray.$Overlay');
goog.require('elemental2.dom.CSSProperties.OpacityUnionType.$Overlay');
goog.require('elemental2.dom.CSSProperties.ZIndexUnionType.$Overlay');
goog.require('elemental2.dom.DomGlobal.$Overlay');
goog.require('elemental2.dom.Event.$Overlay');
goog.require('elemental2.dom.FocusEvent.$Overlay');
goog.require('elemental2.dom.HTMLElement.$Overlay');
goog.require('elemental2.dom.KeyboardEvent.$Overlay');
goog.require('elemental2.dom.MouseEvent.$Overlay');
goog.require('elemental2.dom.MutationRecord.$Overlay');
goog.require('elemental2.dom.Node.$Overlay');
goog.require('java.lang.Integer');
goog.require('java.lang.Object');
goog.require('java.util.ArrayList');
goog.require('java.util.List');
goog.require('java.util.Set');
goog.require('java.util.function.Consumer');
goog.require('javaemul.internal.InternalPreconditions');
goog.require('jsinterop.base.Js');
goog.require('jsinterop.base.JsPropertyMap.$Overlay');
goog.require('nativebootstrap.Equality');
goog.require('nativebootstrap.Util');
goog.require('org.gwtproject.event.shared.HandlerRegistration');
goog.require('org.jboss.elemento.Elements');
goog.require('org.jboss.elemento.EventType');
goog.require('org.jboss.elemento.Key');
goog.require('org.jboss.elemento.ObserverCallback');
goog.require('org.patternfly.popper.Modifier.$Overlay');
goog.require('org.patternfly.popper.Placement');
goog.require('org.patternfly.popper.Popper');
goog.require('org.patternfly.popper.PopperError');
goog.require('org.patternfly.popper.PopperImpl');
goog.require('org.patternfly.popper.TriggerAction');
goog.require('vmbootstrap.Casts');

const PopperBuilder = goog.require('org.patternfly.popper.PopperBuilder$impl');
exports = PopperBuilder;
