goog.module('org.patternfly.component.navigation.ExpandableNavigationGroup');

goog.require('elemental2.dom.Element.$Overlay');
goog.require('elemental2.dom.Event.$Overlay');
goog.require('elemental2.dom.HTMLButtonElement.$Overlay');
goog.require('elemental2.dom.HTMLElement.$Overlay');
goog.require('elemental2.dom.HTMLLIElement.$Overlay');
goog.require('elemental2.dom.HTMLUListElement.$Overlay');
goog.require('elemental2.dom.MouseEvent.$Overlay');
goog.require('elemental2.dom.Node.$Overlay');
goog.require('java.lang.Iterable');
goog.require('java.lang.String');
goog.require('java.util.HashMap');
goog.require('java.util.Map');
goog.require('java.util.function.Consumer');
goog.require('java.util.function.Function');
goog.require('nativebootstrap.Equality');
goog.require('nativebootstrap.Util');
goog.require('org.gwtproject.safehtml.shared.SafeHtml');
goog.require('org.jboss.elemento.By');
goog.require('org.jboss.elemento.Elements');
goog.require('org.jboss.elemento.EventType');
goog.require('org.jboss.elemento.HTMLContainerBuilder');
goog.require('org.jboss.elemento.Id');
goog.require('org.patternfly.component.WithText');
goog.require('org.patternfly.component.divider.Divider');
goog.require('org.patternfly.component.divider.DividerType');
goog.require('org.patternfly.component.navigation.NavigationItem');
goog.require('org.patternfly.component.navigation.NavigationLinkText');
goog.require('org.patternfly.component.navigation.NavigationSubComponent');
goog.require('org.patternfly.core.Aria');
goog.require('org.patternfly.core.Attributes');
goog.require('org.patternfly.core.Dataset');
goog.require('org.patternfly.core.ElementDelegate');
goog.require('org.patternfly.handler.ToggleHandler');
goog.require('org.patternfly.icon.IconSets.fas');
goog.require('org.patternfly.style.Classes');
goog.require('vmbootstrap.Arrays');
goog.require('vmbootstrap.Casts');

const ExpandableNavigationGroup = goog.require('org.patternfly.component.navigation.ExpandableNavigationGroup$impl');
exports = ExpandableNavigationGroup;
