goog.module('org.patternfly.component.navigation.NavigationItem');

goog.require('elemental2.dom.Element.$Overlay');
goog.require('elemental2.dom.Event.$Overlay');
goog.require('elemental2.dom.HTMLAnchorElement.$Overlay');
goog.require('elemental2.dom.HTMLElement.$Overlay');
goog.require('elemental2.dom.HTMLLIElement.$Overlay');
goog.require('elemental2.dom.MouseEvent.$Overlay');
goog.require('elemental2.dom.Node.$Overlay');
goog.require('elemental2.dom.ScrollIntoViewOptions.$Overlay');
goog.require('java.lang.String');
goog.require('nativebootstrap.Equality');
goog.require('nativebootstrap.Util');
goog.require('org.gwtproject.safehtml.shared.SafeHtml');
goog.require('org.jboss.elemento.Elements');
goog.require('org.jboss.elemento.EventType');
goog.require('org.jboss.elemento.HTMLContainerBuilder');
goog.require('org.patternfly.component.WithText');
goog.require('org.patternfly.component.navigation.Navigation');
goog.require('org.patternfly.component.navigation.NavigationLinkText');
goog.require('org.patternfly.component.navigation.NavigationSubComponent');
goog.require('org.patternfly.core.Aria');
goog.require('org.patternfly.core.Dataset');
goog.require('org.patternfly.core.ElementDelegate');
goog.require('org.patternfly.handler.ComponentHandler');
goog.require('org.patternfly.style.Classes');
goog.require('vmbootstrap.Arrays');
goog.require('vmbootstrap.Casts');

const NavigationItem = goog.require('org.patternfly.component.navigation.NavigationItem$impl');
exports = NavigationItem;
