goog.module('elemental2.dom.Document.$Overlay');

goog.require('elemental2.core.JsArray.$Overlay');
goog.require('elemental2.dom.Attr.$Overlay');
goog.require('elemental2.dom.CDATASection.$Overlay');
goog.require('elemental2.dom.CaretPosition.$Overlay');
goog.require('elemental2.dom.Comment.$Overlay');
goog.require('elemental2.dom.DOMImplementation.$Overlay');
goog.require('elemental2.dom.Document.AppendNodesUnionType.$Overlay');
goog.require('elemental2.dom.Document.CreateElementTypeExtensionType.$Overlay');
goog.require('elemental2.dom.Document.CreateElementTypeExtensionUnionType.$Overlay');
goog.require('elemental2.dom.Document.CreateTextNodeDataUnionType.$Overlay');
goog.require('elemental2.dom.Document.PrependNodesUnionType.$Overlay');
goog.require('elemental2.dom.Document.ReplaceChildrenNodesUnionType.$Overlay');
goog.require('elemental2.dom.Document.WriteTextUnionType.$Overlay');
goog.require('elemental2.dom.Document.WritelnTextUnionType.$Overlay');
goog.require('elemental2.dom.DocumentFragment.$Overlay');
goog.require('elemental2.dom.DocumentType.$Overlay');
goog.require('elemental2.dom.Element.$Overlay');
goog.require('elemental2.dom.FontFaceSet.$Overlay');
goog.require('elemental2.dom.HTMLCollection.$Overlay');
goog.require('elemental2.dom.HTMLHeadElement.$Overlay');
goog.require('elemental2.dom.HTMLHtmlElement.$Overlay');
goog.require('elemental2.dom.HTMLScriptElement.$Overlay');
goog.require('elemental2.dom.Node.$Overlay');
goog.require('elemental2.dom.NodeIterator.$Overlay');
goog.require('elemental2.dom.NodeList.$Overlay');
goog.require('elemental2.dom.ProcessingInstruction.$Overlay');
goog.require('elemental2.dom.Selection.$Overlay');
goog.require('elemental2.dom.Text.$Overlay');
goog.require('elemental2.dom.Touch.$Overlay');
goog.require('elemental2.dom.TouchList.$Overlay');
goog.require('elemental2.dom.TreeWalker.$Overlay');
goog.require('elemental2.dom.TrustedHTML.$Overlay');
goog.require('javaemul.internal.InternalPreconditions');
goog.require('jsinterop.base.Js');
goog.require('jsinterop.base.JsArrayLike.$Overlay');
goog.require('jsinterop.base.JsConstructorFn.$Overlay');
goog.require('nativebootstrap.Util');

const $Overlay = goog.require('elemental2.dom.Document.$Overlay$impl');
/** @nodts */
exports = $Overlay;
