goog.module('org.patternfly.component.menu.MenuToggle');

goog.require('elemental2.dom.Element.$Overlay');
goog.require('elemental2.dom.HTMLButtonElement.$Overlay');
goog.require('elemental2.dom.HTMLDivElement.$Overlay');
goog.require('elemental2.dom.HTMLElement.$Overlay');
goog.require('java.lang.String');
goog.require('nativebootstrap.Equality');
goog.require('nativebootstrap.Util');
goog.require('org.jboss.elemento.Elements');
goog.require('org.jboss.elemento.HTMLContainerBuilder');
goog.require('org.patternfly.component.BaseComponent');
goog.require('org.patternfly.component.ComponentType');
goog.require('org.patternfly.component.IconPosition');
goog.require('org.patternfly.component.WithIcon');
goog.require('org.patternfly.component.WithIconAndText');
goog.require('org.patternfly.component.WithText');
goog.require('org.patternfly.component.avatar.Avatar');
goog.require('org.patternfly.component.badge.Badge');
goog.require('org.patternfly.component.menu.MenuToggleAction');
goog.require('org.patternfly.component.menu.MenuToggleCheckbox');
goog.require('org.patternfly.component.menu.MenuToggleType');
goog.require('org.patternfly.core.Aria');
goog.require('org.patternfly.core.Logger');
goog.require('org.patternfly.icon.IconSets.fas');
goog.require('org.patternfly.icon.PredefinedIcon');
goog.require('org.patternfly.style.Classes');
goog.require('org.patternfly.style.Modifiers.Disabled');
goog.require('org.patternfly.style.Modifiers.Secondary');
goog.require('vmbootstrap.Arrays');
goog.require('vmbootstrap.Casts');

const MenuToggle = goog.require('org.patternfly.component.menu.MenuToggle$impl');
exports = MenuToggle;
