goog.module('org.patternfly.showcase.component.CodeEditorComponent');

goog.require('elemental2.dom.HTMLDivElement.$Overlay');
goog.require('java.lang.Class');
goog.require('java.util.function.Supplier');
goog.require('jsinterop.base.JsPropertyMap.$Overlay');
goog.require('nativebootstrap.Util');
goog.require('org.jboss.elemento.Elements');
goog.require('org.jboss.elemento.HTMLContainerBuilder');
goog.require('org.patternfly.component.button.Button');
goog.require('org.patternfly.component.code.CodeEditor');
goog.require('org.patternfly.component.code.CodeEditorAction');
goog.require('org.patternfly.component.code.CodeEditorActions');
goog.require('org.patternfly.component.code.CodeEditorHeader');
goog.require('org.patternfly.component.code.CodeEditorHeaderMain');
goog.require('org.patternfly.component.code.CodeEditorLink');
goog.require('org.patternfly.component.code.CodeEditorLinks');
goog.require('org.patternfly.component.code.CodeEditorTab');
goog.require('org.patternfly.component.code.CodeEditorTabIcon');
goog.require('org.patternfly.component.code.CodeEditorTabText');
goog.require('org.patternfly.icon.IconSets.fas');
goog.require('org.patternfly.showcase.ApiDoc.Type');
goog.require('org.patternfly.showcase.Code');
goog.require('org.patternfly.showcase.Data');
goog.require('org.patternfly.showcase.Snippet');
goog.require('org.patternfly.showcase.SnippetPage');
goog.require('org.patternfly.showcase.component.Component.$Overlay');
goog.require('vmbootstrap.Casts');

const CodeEditorComponent = goog.require('org.patternfly.showcase.component.CodeEditorComponent$impl');
exports = CodeEditorComponent;
