goog.module('org.patternfly.showcase.component.MastheadComponent');

goog.require('elemental2.dom.HTMLDivElement.$Overlay');
goog.require('elemental2.dom.HTMLElement.$Overlay');
goog.require('java.lang.Class');
goog.require('java.lang.String');
goog.require('java.util.function.Supplier');
goog.require('jsinterop.base.JsPropertyMap.$Overlay');
goog.require('nativebootstrap.Util');
goog.require('org.jboss.elemento.Elements');
goog.require('org.jboss.elemento.HTMLContainerBuilder');
goog.require('org.patternfly.component.brand.Brand');
goog.require('org.patternfly.component.button.Button');
goog.require('org.patternfly.component.page.Masthead');
goog.require('org.patternfly.component.page.MastheadBrand');
goog.require('org.patternfly.component.page.MastheadContent');
goog.require('org.patternfly.component.page.MastheadMain');
goog.require('org.patternfly.component.page.MastheadToggle');
goog.require('org.patternfly.layout.flex.Flex');
goog.require('org.patternfly.showcase.ApiDoc.Type');
goog.require('org.patternfly.showcase.Assets');
goog.require('org.patternfly.showcase.Code');
goog.require('org.patternfly.showcase.Data');
goog.require('org.patternfly.showcase.Snippet');
goog.require('org.patternfly.showcase.SnippetPage');
goog.require('org.patternfly.showcase.component.Component.$Overlay');
goog.require('org.patternfly.style.Breakpoint');
goog.require('org.patternfly.style.Breakpoints');
goog.require('org.patternfly.style.Brightness');
goog.require('org.patternfly.style.Classes');
goog.require('org.patternfly.style.Display');
goog.require('org.patternfly.style.Inset');
goog.require('org.patternfly.style.Variable');
goog.require('org.patternfly.style.Variables');
goog.require('vmbootstrap.Arrays');
goog.require('vmbootstrap.Casts');

const MastheadComponent = goog.require('org.patternfly.showcase.component.MastheadComponent$impl');
exports = MastheadComponent;
