goog.module('org.patternfly.showcase.component.MenuComponent');

goog.require('elemental2.dom.Event.$Overlay');
goog.require('elemental2.dom.HTMLDivElement.$Overlay');
goog.require('java.lang.Class');
goog.require('java.lang.String');
goog.require('java.util.List');
goog.require('java.util.function.Function');
goog.require('java.util.function.Supplier');
goog.require('java.util.stream.Collectors');
goog.require('java.util.stream.Stream');
goog.require('jsinterop.base.JsPropertyMap.$Overlay');
goog.require('nativebootstrap.Util');
goog.require('org.jboss.elemento.Elements');
goog.require('org.jboss.elemento.HTMLContainerBuilder');
goog.require('org.patternfly.component.SelectionMode');
goog.require('org.patternfly.component.button.Button');
goog.require('org.patternfly.component.menu.Menu');
goog.require('org.patternfly.component.menu.MenuActionHandler');
goog.require('org.patternfly.component.menu.MenuContent');
goog.require('org.patternfly.component.menu.MenuFooter');
goog.require('org.patternfly.component.menu.MenuGroup');
goog.require('org.patternfly.component.menu.MenuHeader');
goog.require('org.patternfly.component.menu.MenuItem');
goog.require('org.patternfly.component.menu.MenuItemAction');
goog.require('org.patternfly.component.menu.MenuItemType');
goog.require('org.patternfly.component.menu.MenuList');
goog.require('org.patternfly.component.menu.MenuSearch');
goog.require('org.patternfly.component.menu.MenuSearchInput');
goog.require('org.patternfly.component.menu.MenuType');
goog.require('org.patternfly.core.Aria');
goog.require('org.patternfly.handler.ComponentHandler');
goog.require('org.patternfly.handler.MultiSelectHandler');
goog.require('org.patternfly.handler.SelectHandler');
goog.require('org.patternfly.icon.IconSets.fas');
goog.require('org.patternfly.icon.IconSets.patternfly');
goog.require('org.patternfly.showcase.ApiDoc.Type');
goog.require('org.patternfly.showcase.Code');
goog.require('org.patternfly.showcase.Data');
goog.require('org.patternfly.showcase.LoremIpsum');
goog.require('org.patternfly.showcase.Snippet');
goog.require('org.patternfly.showcase.SnippetPage');
goog.require('org.patternfly.showcase.component.Component.$Overlay');
goog.require('vmbootstrap.Casts');

const MenuComponent = goog.require('org.patternfly.showcase.component.MenuComponent$impl');
exports = MenuComponent;
