goog.module('org.patternfly.showcase.component.MenuComponent$impl');

const $Util = goog.require('nativebootstrap.Util$impl');
const SnippetPage = goog.require('org.patternfly.showcase.SnippetPage$impl');

let HTMLDivElement_$Overlay = goog.forwardDeclare('elemental2.dom.HTMLDivElement.$Overlay$impl');
let Class = goog.forwardDeclare('java.lang.Class$impl');
let j_l_String = goog.forwardDeclare('java.lang.String$impl');
let List = goog.forwardDeclare('java.util.List$impl');
let j_u_function_Function = goog.forwardDeclare('java.util.function.Function$impl');
let Supplier = goog.forwardDeclare('java.util.function.Supplier$impl');
let Collectors = goog.forwardDeclare('java.util.stream.Collectors$impl');
let Stream = goog.forwardDeclare('java.util.stream.Stream$impl');
let $Overlay = goog.forwardDeclare('jsinterop.base.JsPropertyMap.$Overlay$impl');
let Elements = goog.forwardDeclare('org.jboss.elemento.Elements$impl');
let HTMLContainerBuilder = goog.forwardDeclare('org.jboss.elemento.HTMLContainerBuilder$impl');
let SelectionMode = goog.forwardDeclare('org.patternfly.component.SelectionMode$impl');
let Button = goog.forwardDeclare('org.patternfly.component.button.Button$impl');
let Menu = goog.forwardDeclare('org.patternfly.component.menu.Menu$impl');
let MenuActionHandler = goog.forwardDeclare('org.patternfly.component.menu.MenuActionHandler$impl');
let MenuContent = goog.forwardDeclare('org.patternfly.component.menu.MenuContent$impl');
let MenuFooter = goog.forwardDeclare('org.patternfly.component.menu.MenuFooter$impl');
let MenuGroup = goog.forwardDeclare('org.patternfly.component.menu.MenuGroup$impl');
let MenuHeader = goog.forwardDeclare('org.patternfly.component.menu.MenuHeader$impl');
let MenuItem = goog.forwardDeclare('org.patternfly.component.menu.MenuItem$impl');
let MenuItemAction = goog.forwardDeclare('org.patternfly.component.menu.MenuItemAction$impl');
let MenuItemType = goog.forwardDeclare('org.patternfly.component.menu.MenuItemType$impl');
let MenuList = goog.forwardDeclare('org.patternfly.component.menu.MenuList$impl');
let MenuSearch = goog.forwardDeclare('org.patternfly.component.menu.MenuSearch$impl');
let MenuSearchInput = goog.forwardDeclare('org.patternfly.component.menu.MenuSearchInput$impl');
let MenuType = goog.forwardDeclare('org.patternfly.component.menu.MenuType$impl');
let Aria = goog.forwardDeclare('org.patternfly.core.Aria$impl');
let ComponentHandler = goog.forwardDeclare('org.patternfly.handler.ComponentHandler$impl');
let MultiSelectHandler = goog.forwardDeclare('org.patternfly.handler.MultiSelectHandler$impl');
let SelectHandler = goog.forwardDeclare('org.patternfly.handler.SelectHandler$impl');
let fas = goog.forwardDeclare('org.patternfly.icon.IconSets.fas$impl');
let patternfly = goog.forwardDeclare('org.patternfly.icon.IconSets.patternfly$impl');
let Type = goog.forwardDeclare('org.patternfly.showcase.ApiDoc.Type$impl');
let Code = goog.forwardDeclare('org.patternfly.showcase.Code$impl');
let Data = goog.forwardDeclare('org.patternfly.showcase.Data$impl');
let LoremIpsum = goog.forwardDeclare('org.patternfly.showcase.LoremIpsum$impl');
let Snippet = goog.forwardDeclare('org.patternfly.showcase.Snippet$impl');
let Component_$Overlay = goog.forwardDeclare('org.patternfly.showcase.component.Component.$Overlay$impl');
let $Casts = goog.forwardDeclare('vmbootstrap.Casts$impl');

class MenuComponent extends SnippetPage {
 /** @protected @nodts */
 constructor() {
  super();
 }
 /** @nodts @return {!MenuComponent} */
 static $create__() {
  MenuComponent.$clinit();
  let $instance = new MenuComponent();
  $instance.$ctor__org_patternfly_showcase_component_MenuComponent__void();
  return $instance;
 }
 /** @nodts */
 $ctor__org_patternfly_showcase_component_MenuComponent__void() {
  this.$ctor__org_patternfly_showcase_SnippetPage__org_patternfly_showcase_component_Component__void(/**@type {Object}*/ ($Casts.$to($Overlay.m_get__$devirt__jsinterop_base_JsPropertyMap__java_lang_String__java_lang_Object(Data.f_components__org_patternfly_showcase_Data, 'menu'), Component_$Overlay)));
  this.m_startExamples__void();
  this.m_addSnippet__org_patternfly_showcase_Snippet__void(Snippet.$create__java_lang_String__java_lang_String__java_lang_String__java_util_function_Supplier('menu-basic', 'Basic menu', Code.m_code__java_lang_String__java_lang_String('menu-basic'), Supplier.$adapt(() =>{
   return /**@type {HTMLDivElement}*/ ($Casts.$to(/**@type {HTMLContainerBuilder<HTMLDivElement>}*/ ($Casts.$to(Elements.m_div__org_jboss_elemento_HTMLContainerBuilder().m_add__org_jboss_elemento_IsElement__org_jboss_elemento_TypedBuilder(Menu.m_menu__org_patternfly_component_SelectionMode__org_patternfly_component_menu_Menu(SelectionMode.f_click__org_patternfly_component_SelectionMode).m_onSingleSelect__org_patternfly_handler_SelectHandler__org_patternfly_component_menu_Menu(SelectHandler.$adapt((/** Event */ e, item, /** boolean */ selected) =>{
    let item_1 = /**@type {MenuItem}*/ ($Casts.$to(item, MenuItem));
    goog.global.console.log('Item ' + j_l_String.m_valueOf__java_lang_Object__java_lang_String(item_1.f_id__org_patternfly_component_menu_MenuItem) + ' selected');
   })).m_addContent__org_patternfly_component_menu_MenuContent__org_patternfly_component_menu_Menu(MenuContent.m_menuContent__org_patternfly_component_menu_MenuContent().m_addList__org_patternfly_component_menu_MenuList__org_patternfly_component_menu_MenuContent(MenuList.m_menuList__org_patternfly_component_menu_MenuList().m_addItem__org_patternfly_component_menu_MenuItem__org_patternfly_component_menu_MenuList(MenuItem.m_actionMenuItem__java_lang_String__java_lang_String__org_patternfly_component_menu_MenuItem('item-0', 'Action').m_onClick__org_patternfly_handler_ComponentHandler__org_patternfly_component_menu_MenuItem(ComponentHandler.$adapt((/** Event */ e_1, actionItem) =>{
    let actionItem_1 = /**@type {MenuItem}*/ ($Casts.$to(actionItem, MenuItem));
    goog.global.console.log('Clicked on action item ' + j_l_String.m_valueOf__java_lang_Object__java_lang_String(actionItem_1.f_id__org_patternfly_component_menu_MenuItem));
   }))).m_addItem__org_patternfly_component_menu_MenuItem__org_patternfly_component_menu_MenuList(MenuItem.m_linkMenuItem__java_lang_String__java_lang_String__java_lang_String__org_patternfly_component_menu_MenuItem('item-1', 'Link', '#item-1').m_onClick__org_patternfly_handler_ComponentHandler__org_patternfly_component_menu_MenuItem(ComponentHandler.$adapt((/** Event */ e_2, item_2) =>{
    let item_3 = /**@type {MenuItem}*/ ($Casts.$to(item_2, MenuItem));
    e_2.preventDefault();
   }))).m_addItem__org_patternfly_component_menu_MenuItem__org_patternfly_component_menu_MenuList(/**@type {MenuItem}*/ ($Casts.$to(MenuItem.m_actionMenuItem__java_lang_String__java_lang_String__org_patternfly_component_menu_MenuItem('item-2', 'Disabled action').m_disabled__org_jboss_elemento_TypedBuilder(), MenuItem))).m_addItem__org_patternfly_component_menu_MenuItem__org_patternfly_component_menu_MenuList(/**@type {MenuItem}*/ ($Casts.$to(MenuItem.m_linkMenuItem__java_lang_String__java_lang_String__java_lang_String__org_patternfly_component_menu_MenuItem('item-3', 'Disabled link', '#item-3').m_disabled__org_jboss_elemento_TypedBuilder(), MenuItem)))))), HTMLContainerBuilder)).m_element__elemental2_dom_HTMLElement(), HTMLDivElement_$Overlay));
  })));
  this.m_addSnippet__org_patternfly_showcase_Snippet__void(Snippet.$create__java_lang_String__java_lang_String__java_lang_String__java_util_function_Supplier('menu-danger', 'Danger menu item', Code.m_code__java_lang_String__java_lang_String('menu-danger'), Supplier.$adapt(() =>{
   return /**@type {HTMLDivElement}*/ ($Casts.$to(/**@type {HTMLContainerBuilder<HTMLDivElement>}*/ ($Casts.$to(Elements.m_div__org_jboss_elemento_HTMLContainerBuilder().m_add__org_jboss_elemento_IsElement__org_jboss_elemento_TypedBuilder(Menu.m_menu__org_patternfly_component_SelectionMode__org_patternfly_component_menu_Menu(SelectionMode.f_click__org_patternfly_component_SelectionMode).m_addContent__org_patternfly_component_menu_MenuContent__org_patternfly_component_menu_Menu(MenuContent.m_menuContent__org_patternfly_component_menu_MenuContent().m_addList__org_patternfly_component_menu_MenuList__org_patternfly_component_menu_MenuContent(MenuList.m_menuList__org_patternfly_component_menu_MenuList().m_addItem__org_patternfly_component_menu_MenuItem__org_patternfly_component_menu_MenuList(MenuItem.m_actionMenuItem__java_lang_String__java_lang_String__org_patternfly_component_menu_MenuItem('item-0', 'Action 1')).m_addItem__org_patternfly_component_menu_MenuItem__org_patternfly_component_menu_MenuList(MenuItem.m_actionMenuItem__java_lang_String__java_lang_String__org_patternfly_component_menu_MenuItem('item-1', 'Action 2')).m_addDivider__org_patternfly_component_menu_MenuList().m_addItem__org_patternfly_component_menu_MenuItem__org_patternfly_component_menu_MenuList(MenuItem.m_actionMenuItem__java_lang_String__java_lang_String__org_patternfly_component_menu_MenuItem('item-2', 'Delete').m_danger__org_patternfly_component_menu_MenuItem())))), HTMLContainerBuilder)).m_element__elemental2_dom_HTMLElement(), HTMLDivElement_$Overlay));
  })));
  this.m_addSnippet__org_patternfly_showcase_Snippet__void(Snippet.$create__java_lang_String__java_lang_String__java_lang_String__java_util_function_Supplier('menu-icons', 'With icons', Code.m_code__java_lang_String__java_lang_String('menu-icons'), Supplier.$adapt(() =>{
   return /**@type {HTMLDivElement}*/ ($Casts.$to(/**@type {HTMLContainerBuilder<HTMLDivElement>}*/ ($Casts.$to(Elements.m_div__org_jboss_elemento_HTMLContainerBuilder().m_add__org_jboss_elemento_IsElement__org_jboss_elemento_TypedBuilder(Menu.m_menu__org_patternfly_component_SelectionMode__org_patternfly_component_menu_Menu(SelectionMode.f_click__org_patternfly_component_SelectionMode).m_addContent__org_patternfly_component_menu_MenuContent__org_patternfly_component_menu_Menu(MenuContent.m_menuContent__org_patternfly_component_menu_MenuContent().m_addList__org_patternfly_component_menu_MenuList__org_patternfly_component_menu_MenuContent(MenuList.m_menuList__org_patternfly_component_menu_MenuList().m_addItem__org_patternfly_component_menu_MenuItem__org_patternfly_component_menu_MenuList(/**@type {MenuItem}*/ ($Casts.$to(MenuItem.m_actionMenuItem__java_lang_String__java_lang_String__org_patternfly_component_menu_MenuItem('item-0', 'Item 1').m_icon__org_patternfly_icon_PredefinedIcon__org_jboss_elemento_TypedBuilder(fas.m_codeBranch__org_patternfly_icon_PredefinedIcon()), MenuItem))).m_addItem__org_patternfly_component_menu_MenuItem__org_patternfly_component_menu_MenuList(/**@type {MenuItem}*/ ($Casts.$to(MenuItem.m_actionMenuItem__java_lang_String__java_lang_String__org_patternfly_component_menu_MenuItem('item-1', 'Container image').m_icon__org_patternfly_icon_PredefinedIcon__org_jboss_elemento_TypedBuilder(fas.m_layerGroup__org_patternfly_icon_PredefinedIcon()), MenuItem))).m_addItem__org_patternfly_component_menu_MenuItem__org_patternfly_component_menu_MenuList(/**@type {MenuItem}*/ ($Casts.$to(MenuItem.m_actionMenuItem__java_lang_String__java_lang_String__org_patternfly_component_menu_MenuItem('item-2', 'From Dockerfile').m_icon__org_patternfly_icon_PredefinedIcon__org_jboss_elemento_TypedBuilder(fas.m_cube__org_patternfly_icon_PredefinedIcon()), MenuItem)))))), HTMLContainerBuilder)).m_element__elemental2_dom_HTMLElement(), HTMLDivElement_$Overlay));
  })));
  this.m_addSnippet__org_patternfly_showcase_Snippet__void(Snippet.$create__java_lang_String__java_lang_String__java_lang_String__java_util_function_Supplier('menu-actions', 'With action', Code.m_code__java_lang_String__java_lang_String('menu-actions'), Supplier.$adapt(() =>{
   return /**@type {HTMLDivElement}*/ ($Casts.$to(/**@type {HTMLContainerBuilder<HTMLDivElement>}*/ ($Casts.$to(Elements.m_div__org_jboss_elemento_HTMLContainerBuilder().m_add__org_jboss_elemento_IsElement__org_jboss_elemento_TypedBuilder(Menu.m_menu__org_patternfly_component_SelectionMode__org_patternfly_component_menu_Menu(SelectionMode.f_multi__org_patternfly_component_SelectionMode).m_onAction__org_patternfly_component_menu_MenuActionHandler__org_patternfly_component_menu_Menu(MenuActionHandler.$adapt((/** Menu */ menu, /** MenuItem */ item_4, /** MenuItemAction */ itemAction) =>{
    goog.global.console.log('Action ' + j_l_String.m_valueOf__java_lang_Object__java_lang_String(itemAction.f_id__org_patternfly_component_menu_MenuItemAction) + ' on item ' + j_l_String.m_valueOf__java_lang_Object__java_lang_String(item_4.f_id__org_patternfly_component_menu_MenuItem) + ' clicked');
   })).m_addContent__org_patternfly_component_menu_MenuContent__org_patternfly_component_menu_Menu(MenuContent.m_menuContent__org_patternfly_component_menu_MenuContent().m_addGroup__org_patternfly_component_menu_MenuGroup__org_patternfly_component_menu_MenuContent(MenuGroup.m_menuGroup__java_lang_String__org_patternfly_component_menu_MenuGroup('Actions').m_addList__org_patternfly_component_menu_MenuList__org_patternfly_component_menu_MenuGroup(MenuList.m_menuList__org_patternfly_component_menu_MenuList().m_addItem__org_patternfly_component_menu_MenuItem__org_patternfly_component_menu_MenuList(MenuItem.m_actionMenuItem__java_lang_String__java_lang_String__org_patternfly_component_menu_MenuItem('item-0', 'Item 1').m_description__java_lang_String__org_patternfly_component_menu_MenuItem('This is a description').m_addAction__org_patternfly_component_menu_MenuItemAction__org_patternfly_component_menu_MenuItem(/**@type {MenuItemAction}*/ ($Casts.$to(MenuItemAction.m_menuItemAction__java_lang_String__org_patternfly_icon_PredefinedIcon__org_patternfly_component_menu_MenuItemAction('action-0', fas.m_codeBranch__org_patternfly_icon_PredefinedIcon()).m_aria__java_lang_String__java_lang_String__org_jboss_elemento_TypedBuilder(Aria.f_label__org_patternfly_core_Aria, 'Code'), MenuItemAction)).m_onClick__org_patternfly_handler_ComponentHandler__org_patternfly_component_menu_MenuItemAction(ComponentHandler.$adapt((/** Event */ e_3, itemAction_1) =>{
    let itemAction_2 = /**@type {MenuItemAction}*/ ($Casts.$to(itemAction_1, MenuItemAction));
    goog.global.console.log('Code action clicked');
   })))).m_addItem__org_patternfly_component_menu_MenuItem__org_patternfly_component_menu_MenuList(/**@type {MenuItem}*/ ($Casts.$to(MenuItem.m_actionMenuItem__java_lang_String__java_lang_String__org_patternfly_component_menu_MenuItem('item-1', 'Item 2').m_description__java_lang_String__org_patternfly_component_menu_MenuItem('This is a description').m_disabled__org_jboss_elemento_TypedBuilder(), MenuItem)).m_addAction__org_patternfly_component_menu_MenuItemAction__org_patternfly_component_menu_MenuItem(MenuItemAction.m_menuItemAction__java_lang_String__org_patternfly_icon_PredefinedIcon__org_patternfly_component_menu_MenuItemAction('action-1', patternfly.m_bell__org_patternfly_icon_PredefinedIcon()))).m_addItem__org_patternfly_component_menu_MenuItem__org_patternfly_component_menu_MenuList(MenuItem.m_actionMenuItem__java_lang_String__java_lang_String__org_patternfly_component_menu_MenuItem('item-2', 'Item 3').m_addAction__org_patternfly_component_menu_MenuItemAction__org_patternfly_component_menu_MenuItem(MenuItemAction.m_menuItemAction__java_lang_String__org_patternfly_icon_PredefinedIcon__org_patternfly_component_menu_MenuItemAction('action-2', fas.m_clipboard__org_patternfly_icon_PredefinedIcon()))).m_addItem__org_patternfly_component_menu_MenuItem__org_patternfly_component_menu_MenuList(MenuItem.m_actionMenuItem__java_lang_String__java_lang_String__org_patternfly_component_menu_MenuItem('item-3', 'Item 4').m_description__java_lang_String__org_patternfly_component_menu_MenuItem('This is a description').m_addAction__org_patternfly_component_menu_MenuItemAction__org_patternfly_component_menu_MenuItem(MenuItemAction.m_menuItemAction__java_lang_String__org_patternfly_icon_PredefinedIcon__org_patternfly_component_menu_MenuItemAction('action-3', fas.m_bars__org_patternfly_icon_PredefinedIcon()))))))), HTMLContainerBuilder)).m_element__elemental2_dom_HTMLElement(), HTMLDivElement_$Overlay));
  })));
  this.m_addSnippet__org_patternfly_showcase_Snippet__void(Snippet.$create__java_lang_String__java_lang_String__java_lang_String__java_util_function_Supplier('menu-links', 'With links', Code.m_code__java_lang_String__java_lang_String('menu-links'), Supplier.$adapt(() =>{
   return /**@type {HTMLDivElement}*/ ($Casts.$to(/**@type {HTMLContainerBuilder<HTMLDivElement>}*/ ($Casts.$to(Elements.m_div__org_jboss_elemento_HTMLContainerBuilder().m_add__org_jboss_elemento_IsElement__org_jboss_elemento_TypedBuilder(Menu.m_menu__org_patternfly_component_SelectionMode__org_patternfly_component_menu_Menu(SelectionMode.f_click__org_patternfly_component_SelectionMode).m_addContent__org_patternfly_component_menu_MenuContent__org_patternfly_component_menu_Menu(MenuContent.m_menuContent__org_patternfly_component_menu_MenuContent().m_addList__org_patternfly_component_menu_MenuList__org_patternfly_component_menu_MenuContent(MenuList.m_menuList__org_patternfly_component_menu_MenuList().m_addItem__org_patternfly_component_menu_MenuItem__org_patternfly_component_menu_MenuList(MenuItem.m_linkMenuItem__java_lang_String__java_lang_String__java_lang_String__org_patternfly_component_menu_MenuItem('item-0', 'Link 1', '#item-0').m_external__org_patternfly_component_menu_MenuItem()).m_addItem__org_patternfly_component_menu_MenuItem__org_patternfly_component_menu_MenuList(MenuItem.m_linkMenuItem__java_lang_String__java_lang_String__java_lang_String__org_patternfly_component_menu_MenuItem('item-1', 'Link 2', '#item-1').m_external__org_patternfly_component_menu_MenuItem()).m_addItem__org_patternfly_component_menu_MenuItem__org_patternfly_component_menu_MenuList(MenuItem.m_linkMenuItem__java_lang_String__java_lang_String__java_lang_String__org_patternfly_component_menu_MenuItem('item-2', 'Link 3', '#item-2'))))), HTMLContainerBuilder)).m_element__elemental2_dom_HTMLElement(), HTMLDivElement_$Overlay));
  })));
  this.m_addSnippet__org_patternfly_showcase_Snippet__void(Snippet.$create__java_lang_String__java_lang_String__java_lang_String__java_util_function_Supplier('menu-descriptions', 'With descriptions', Code.m_code__java_lang_String__java_lang_String('menu-descriptions'), Supplier.$adapt(() =>{
   return /**@type {HTMLDivElement}*/ ($Casts.$to(/**@type {HTMLContainerBuilder<HTMLDivElement>}*/ ($Casts.$to(Elements.m_div__org_jboss_elemento_HTMLContainerBuilder().m_add__org_jboss_elemento_IsElement__org_jboss_elemento_TypedBuilder(Menu.m_menu__org_patternfly_component_SelectionMode__org_patternfly_component_menu_Menu(SelectionMode.f_click__org_patternfly_component_SelectionMode).m_addContent__org_patternfly_component_menu_MenuContent__org_patternfly_component_menu_Menu(MenuContent.m_menuContent__org_patternfly_component_menu_MenuContent().m_addList__org_patternfly_component_menu_MenuList__org_patternfly_component_menu_MenuContent(MenuList.m_menuList__org_patternfly_component_menu_MenuList().m_addItem__org_patternfly_component_menu_MenuItem__org_patternfly_component_menu_MenuList(/**@type {MenuItem}*/ ($Casts.$to(MenuItem.m_actionMenuItem__java_lang_String__java_lang_String__org_patternfly_component_menu_MenuItem('item-0', 'Action 1').m_icon__org_patternfly_icon_PredefinedIcon__org_jboss_elemento_TypedBuilder(fas.m_codeBranch__org_patternfly_icon_PredefinedIcon()), MenuItem)).m_description__java_lang_String__org_patternfly_component_menu_MenuItem('Description')).m_addItem__org_patternfly_component_menu_MenuItem__org_patternfly_component_menu_MenuList(/**@type {MenuItem}*/ ($Casts.$to(/**@type {MenuItem}*/ ($Casts.$to(MenuItem.m_actionMenuItem__java_lang_String__java_lang_String__org_patternfly_component_menu_MenuItem('item-1', 'Action 2 disabled').m_icon__org_patternfly_icon_PredefinedIcon__org_jboss_elemento_TypedBuilder(fas.m_codeBranch__org_patternfly_icon_PredefinedIcon()), MenuItem)).m_description__java_lang_String__org_patternfly_component_menu_MenuItem('Description').m_disabled__org_jboss_elemento_TypedBuilder(), MenuItem))).m_addItem__org_patternfly_component_menu_MenuItem__org_patternfly_component_menu_MenuList(/**@type {MenuItem}*/ ($Casts.$to(MenuItem.m_actionMenuItem__java_lang_String__java_lang_String__org_patternfly_component_menu_MenuItem('item-2', 'Action 3').m_icon__org_patternfly_icon_PredefinedIcon__org_jboss_elemento_TypedBuilder(fas.m_codeBranch__org_patternfly_icon_PredefinedIcon()), MenuItem)).m_description__java_lang_String__org_patternfly_component_menu_MenuItem(LoremIpsum.m_words__int__java_lang_String(50)))))), HTMLContainerBuilder)).m_element__elemental2_dom_HTMLElement(), HTMLDivElement_$Overlay));
  })));
  this.m_addSnippet__org_patternfly_showcase_Snippet__void(Snippet.$create__java_lang_String__java_lang_String__java_lang_String__java_util_function_Supplier('menu-checkbox', 'Item checkbox', Code.m_code__java_lang_String__java_lang_String('menu-checkbox'), Supplier.$adapt(() =>{
   return /**@type {HTMLDivElement}*/ ($Casts.$to(/**@type {HTMLContainerBuilder<HTMLDivElement>}*/ ($Casts.$to(Elements.m_div__org_jboss_elemento_HTMLContainerBuilder().m_add__org_jboss_elemento_IsElement__org_jboss_elemento_TypedBuilder(Menu.m_menu__org_patternfly_component_SelectionMode__org_patternfly_component_menu_Menu(SelectionMode.f_multi__org_patternfly_component_SelectionMode).m_onMultiSelect__org_patternfly_handler_MultiSelectHandler__org_patternfly_component_menu_Menu(MultiSelectHandler.$adapt((/** Event */ e_4, menu_1, /** List<MenuItem> */ menuItems) =>{
    let menu_2 = /**@type {Menu}*/ ($Casts.$to(menu_1, Menu));
    goog.global.console.log('### Selected items: ' + j_l_String.m_valueOf__java_lang_Object__java_lang_String(/**@type {?string}*/ ($Casts.$to(/**@type {Stream<?string>}*/ (menuItems.m_stream__java_util_stream_Stream().m_map__java_util_function_Function__java_util_stream_Stream(j_u_function_Function.$adapt((mi) =>{
     let mi_1 = /**@type {MenuItem}*/ ($Casts.$to(mi, MenuItem));
     return mi_1.f_id__org_patternfly_component_menu_MenuItem;
    }))).m_collect__java_util_stream_Collector__java_lang_Object(Collectors.m_joining__java_lang_CharSequence__java_util_stream_Collector(', ')), j_l_String))));
   })).m_addContent__org_patternfly_component_menu_MenuContent__org_patternfly_component_menu_Menu(MenuContent.m_menuContent__org_patternfly_component_menu_MenuContent().m_addList__org_patternfly_component_menu_MenuList__org_patternfly_component_menu_MenuContent(MenuList.m_menuList__org_patternfly_component_menu_MenuList().m_addItem__org_patternfly_component_menu_MenuItem__org_patternfly_component_menu_MenuList(MenuItem.m_checkboxMenuItem__java_lang_String__java_lang_String__org_patternfly_component_menu_MenuItem('item-0', 'Checkbox 1').m_onClick__org_patternfly_handler_ComponentHandler__org_patternfly_component_menu_MenuItem(ComponentHandler.$adapt((/** Event */ e_5, mi_2) =>{
    let mi_3 = /**@type {MenuItem}*/ ($Casts.$to(mi_2, MenuItem));
    goog.global.console.log('Clicked on item ' + j_l_String.m_valueOf__java_lang_Object__java_lang_String(mi_3.f_id__org_patternfly_component_menu_MenuItem));
   }))).m_addItem__org_patternfly_component_menu_MenuItem__org_patternfly_component_menu_MenuList(MenuItem.m_checkboxMenuItem__java_lang_String__java_lang_String__org_patternfly_component_menu_MenuItem('item-1', 'Checkbox 2').m_onClick__org_patternfly_handler_ComponentHandler__org_patternfly_component_menu_MenuItem(ComponentHandler.$adapt((/** Event */ e_6, mi_4) =>{
    let mi_5 = /**@type {MenuItem}*/ ($Casts.$to(mi_4, MenuItem));
    goog.global.console.log('Clicked on item ' + j_l_String.m_valueOf__java_lang_Object__java_lang_String(mi_5.f_id__org_patternfly_component_menu_MenuItem));
   }))).m_addItem__org_patternfly_component_menu_MenuItem__org_patternfly_component_menu_MenuList(/**@type {MenuItem}*/ ($Casts.$to(MenuItem.m_checkboxMenuItem__java_lang_String__java_lang_String__org_patternfly_component_menu_MenuItem('item-2', 'Checkbox 3').m_onClick__org_patternfly_handler_ComponentHandler__org_patternfly_component_menu_MenuItem(ComponentHandler.$adapt((/** Event */ e_7, mi_6) =>{
    let mi_7 = /**@type {MenuItem}*/ ($Casts.$to(mi_6, MenuItem));
    goog.global.console.log('Clicked on item ' + j_l_String.m_valueOf__java_lang_Object__java_lang_String(mi_7.f_id__org_patternfly_component_menu_MenuItem));
   })).m_disabled__org_jboss_elemento_TypedBuilder(), MenuItem)))))), HTMLContainerBuilder)).m_element__elemental2_dom_HTMLElement(), HTMLDivElement_$Overlay));
  })));
  this.m_addSnippet__org_patternfly_showcase_Snippet__void(Snippet.$create__java_lang_String__java_lang_String__java_lang_String__java_util_function_Supplier('menu-footer', 'Menu footer', Code.m_code__java_lang_String__java_lang_String('menu-footer'), Supplier.$adapt(() =>{
   return /**@type {HTMLDivElement}*/ ($Casts.$to(/**@type {HTMLContainerBuilder<HTMLDivElement>}*/ ($Casts.$to(Elements.m_div__org_jboss_elemento_HTMLContainerBuilder().m_add__org_jboss_elemento_IsElement__org_jboss_elemento_TypedBuilder(Menu.m_menu__org_patternfly_component_SelectionMode__org_patternfly_component_menu_Menu(SelectionMode.f_click__org_patternfly_component_SelectionMode).m_addContent__org_patternfly_component_menu_MenuContent__org_patternfly_component_menu_Menu(MenuContent.m_menuContent__org_patternfly_component_menu_MenuContent().m_addList__org_patternfly_component_menu_MenuList__org_patternfly_component_menu_MenuContent(MenuList.m_menuList__org_patternfly_component_menu_MenuList().m_addItem__org_patternfly_component_menu_MenuItem__org_patternfly_component_menu_MenuList(MenuItem.m_actionMenuItem__java_lang_String__java_lang_String__org_patternfly_component_menu_MenuItem('item-0', 'Action')).m_addItem__org_patternfly_component_menu_MenuItem__org_patternfly_component_menu_MenuList(MenuItem.m_linkMenuItem__java_lang_String__java_lang_String__java_lang_String__org_patternfly_component_menu_MenuItem('item-1', 'Link', '#item-1')).m_addItem__org_patternfly_component_menu_MenuItem__org_patternfly_component_menu_MenuList(/**@type {MenuItem}*/ ($Casts.$to(MenuItem.m_actionMenuItem__java_lang_String__java_lang_String__org_patternfly_component_menu_MenuItem('item-2', 'Disabled action').m_disabled__org_jboss_elemento_TypedBuilder(), MenuItem))).m_addItem__org_patternfly_component_menu_MenuItem__org_patternfly_component_menu_MenuList(/**@type {MenuItem}*/ ($Casts.$to(MenuItem.m_linkMenuItem__java_lang_String__java_lang_String__java_lang_String__org_patternfly_component_menu_MenuItem('item-3', 'Disabled link', '#item-3').m_disabled__org_jboss_elemento_TypedBuilder(), MenuItem))))).m_addFooter__org_patternfly_component_menu_MenuFooter__org_patternfly_component_menu_Menu(/**@type {MenuFooter}*/ ($Casts.$to(MenuFooter.m_menuFooter__org_patternfly_component_menu_MenuFooter().m_add__org_jboss_elemento_IsElement__org_jboss_elemento_TypedBuilder(/**@type {Button}*/ ($Casts.$to(Button.m_button__java_lang_String__org_patternfly_component_button_Button('Action').m_link__org_patternfly_component_button_Button().m_inline__org_jboss_elemento_TypedBuilder(), Button))), MenuFooter)))), HTMLContainerBuilder)).m_element__elemental2_dom_HTMLElement(), HTMLDivElement_$Overlay));
  })));
  this.m_addSnippet__org_patternfly_showcase_Snippet__void(Snippet.$create__java_lang_String__java_lang_String__java_lang_String__java_util_function_Supplier('menu-separator', 'Separated items', Code.m_code__java_lang_String__java_lang_String('menu-separator'), Supplier.$adapt(() =>{
   return /**@type {HTMLDivElement}*/ ($Casts.$to(/**@type {HTMLContainerBuilder<HTMLDivElement>}*/ ($Casts.$to(Elements.m_div__org_jboss_elemento_HTMLContainerBuilder().m_add__org_jboss_elemento_IsElement__org_jboss_elemento_TypedBuilder(Menu.m_menu__org_patternfly_component_SelectionMode__org_patternfly_component_menu_Menu(SelectionMode.f_click__org_patternfly_component_SelectionMode).m_addContent__org_patternfly_component_menu_MenuContent__org_patternfly_component_menu_Menu(MenuContent.m_menuContent__org_patternfly_component_menu_MenuContent().m_addList__org_patternfly_component_menu_MenuList__org_patternfly_component_menu_MenuContent(MenuList.m_menuList__org_patternfly_component_menu_MenuList().m_addItem__org_patternfly_component_menu_MenuItem__org_patternfly_component_menu_MenuList(MenuItem.m_actionMenuItem__java_lang_String__java_lang_String__org_patternfly_component_menu_MenuItem('item-0', 'Action 1')).m_addItem__org_patternfly_component_menu_MenuItem__org_patternfly_component_menu_MenuList(MenuItem.m_actionMenuItem__java_lang_String__java_lang_String__org_patternfly_component_menu_MenuItem('item-1', 'Action 2')).m_addDivider__org_patternfly_component_menu_MenuList().m_addItem__org_patternfly_component_menu_MenuItem__org_patternfly_component_menu_MenuList(MenuItem.m_actionMenuItem__java_lang_String__java_lang_String__org_patternfly_component_menu_MenuItem('item-2', 'Action 3'))))), HTMLContainerBuilder)).m_element__elemental2_dom_HTMLElement(), HTMLDivElement_$Overlay));
  })));
  this.m_addSnippet__org_patternfly_showcase_Snippet__void(Snippet.$create__java_lang_String__java_lang_String__java_lang_String__java_util_function_Supplier('menu-titled-groups', 'Titled groups of items', Code.m_code__java_lang_String__java_lang_String('menu-titled-groups'), Supplier.$adapt(() =>{
   return /**@type {HTMLDivElement}*/ ($Casts.$to(/**@type {HTMLContainerBuilder<HTMLDivElement>}*/ ($Casts.$to(Elements.m_div__org_jboss_elemento_HTMLContainerBuilder().m_add__org_jboss_elemento_IsElement__org_jboss_elemento_TypedBuilder(Menu.m_menu__org_patternfly_component_SelectionMode__org_patternfly_component_menu_Menu(SelectionMode.f_click__org_patternfly_component_SelectionMode).m_addContent__org_patternfly_component_menu_MenuContent__org_patternfly_component_menu_Menu(MenuContent.m_menuContent__org_patternfly_component_menu_MenuContent().m_addGroup__org_patternfly_component_menu_MenuGroup__org_patternfly_component_menu_MenuContent(MenuGroup.m_menuGroup__org_patternfly_component_menu_MenuGroup().m_addList__org_patternfly_component_menu_MenuList__org_patternfly_component_menu_MenuGroup(MenuList.m_menuList__org_patternfly_component_menu_MenuList().m_addItem__org_patternfly_component_menu_MenuItem__org_patternfly_component_menu_MenuList(MenuItem.m_linkMenuItem__java_lang_String__java_lang_String__java_lang_String__org_patternfly_component_menu_MenuItem('item-0', 'Link not in group', '#item-0')))).m_addDivider__org_patternfly_component_menu_MenuContent().m_addGroup__org_patternfly_component_menu_MenuGroup__org_patternfly_component_menu_MenuContent(MenuGroup.m_menuGroup__java_lang_String__org_patternfly_component_menu_MenuGroup('Group 1').m_addList__org_patternfly_component_menu_MenuList__org_patternfly_component_menu_MenuGroup(MenuList.m_menuList__org_patternfly_component_menu_MenuList().m_add__org_patternfly_component_menu_MenuItem__org_patternfly_component_menu_MenuList(MenuItem.m_linkMenuItem__java_lang_String__java_lang_String__java_lang_String__org_patternfly_component_menu_MenuItem('item-10', 'Link 1', '#item-10')).m_add__org_patternfly_component_menu_MenuItem__org_patternfly_component_menu_MenuList(MenuItem.m_linkMenuItem__java_lang_String__java_lang_String__java_lang_String__org_patternfly_component_menu_MenuItem('item-11', 'Link 2', '#item-11')))).m_addDivider__org_patternfly_component_menu_MenuContent().m_addGroup__org_patternfly_component_menu_MenuGroup__org_patternfly_component_menu_MenuContent(MenuGroup.m_menuGroup__java_lang_String__org_patternfly_component_menu_MenuGroup('Group 2').m_addList__org_patternfly_component_menu_MenuList__org_patternfly_component_menu_MenuGroup(MenuList.m_menuList__org_patternfly_component_menu_MenuList().m_add__org_patternfly_component_menu_MenuItem__org_patternfly_component_menu_MenuList(MenuItem.m_linkMenuItem__java_lang_String__java_lang_String__java_lang_String__org_patternfly_component_menu_MenuItem('item-20', 'Link 1', '#item-20')).m_add__org_patternfly_component_menu_MenuItem__org_patternfly_component_menu_MenuList(MenuItem.m_linkMenuItem__java_lang_String__java_lang_String__java_lang_String__org_patternfly_component_menu_MenuItem('item-21', 'Link 2', '#item-21')))))), HTMLContainerBuilder)).m_element__elemental2_dom_HTMLElement(), HTMLDivElement_$Overlay));
  })));
  this.m_addSnippet__org_patternfly_showcase_Snippet__void(Snippet.$create__java_lang_String__java_lang_String__java_lang_String__java_util_function_Supplier('menu-favorites', 'With favorites', Code.m_code__java_lang_String__java_lang_String('menu-favorites'), Supplier.$adapt(() =>{
   return /**@type {HTMLDivElement}*/ ($Casts.$to(/**@type {HTMLContainerBuilder<HTMLDivElement>}*/ ($Casts.$to(Elements.m_div__org_jboss_elemento_HTMLContainerBuilder().m_add__org_jboss_elemento_IsElement__org_jboss_elemento_TypedBuilder(Menu.m_menu__org_patternfly_component_SelectionMode__org_patternfly_component_menu_Menu(SelectionMode.f_click__org_patternfly_component_SelectionMode).m_onSingleSelect__org_patternfly_handler_SelectHandler__org_patternfly_component_menu_Menu(SelectHandler.$adapt((/** Event */ e_8, item_5, /** boolean */ selected_1) =>{
    let item_6 = /**@type {MenuItem}*/ ($Casts.$to(item_5, MenuItem));
    goog.global.console.log('Item ' + j_l_String.m_valueOf__java_lang_Object__java_lang_String(item_6.f_id__org_patternfly_component_menu_MenuItem) + ' selected');
   })).m_onAction__org_patternfly_component_menu_MenuActionHandler__org_patternfly_component_menu_Menu(MenuActionHandler.$adapt((/** Menu */ menu_3, /** MenuItem */ item_7, /** MenuItemAction */ itemAction_3) =>{
    goog.global.console.log('Action ' + j_l_String.m_valueOf__java_lang_Object__java_lang_String(itemAction_3.f_id__org_patternfly_component_menu_MenuItemAction) + ' on item ' + j_l_String.m_valueOf__java_lang_Object__java_lang_String(item_7.f_id__org_patternfly_component_menu_MenuItem) + ' clicked');
   })).m_favorites__org_patternfly_component_menu_Menu().m_addContent__org_patternfly_component_menu_MenuContent__org_patternfly_component_menu_Menu(MenuContent.m_menuContent__org_patternfly_component_menu_MenuContent().m_addGroup__org_patternfly_component_menu_MenuGroup__org_patternfly_component_menu_MenuContent(MenuGroup.m_menuGroup__java_lang_String__org_patternfly_component_menu_MenuGroup('All actions').m_addList__org_patternfly_component_menu_MenuList__org_patternfly_component_menu_MenuGroup(MenuList.m_menuList__org_patternfly_component_menu_MenuList().m_addItem__org_patternfly_component_menu_MenuItem__org_patternfly_component_menu_MenuList(MenuItem.m_actionMenuItem__java_lang_String__java_lang_String__org_patternfly_component_menu_MenuItem('item-0', 'Item 1').m_description__java_lang_String__org_patternfly_component_menu_MenuItem('Description 1').m_addAction__org_patternfly_component_menu_MenuItemAction__org_patternfly_component_menu_MenuItem(MenuItemAction.m_menuItemAction__java_lang_String__org_patternfly_icon_PredefinedIcon__org_patternfly_component_menu_MenuItemAction('action-0', fas.m_bars__org_patternfly_icon_PredefinedIcon()))).m_addItem__org_patternfly_component_menu_MenuItem__org_patternfly_component_menu_MenuList(MenuItem.m_actionMenuItem__java_lang_String__java_lang_String__org_patternfly_component_menu_MenuItem('item-1', 'Item 2').m_onClick__org_patternfly_handler_ComponentHandler__org_patternfly_component_menu_MenuItem(ComponentHandler.$adapt((/** Event */ e_9, item_8) =>{
    let item_9 = /**@type {MenuItem}*/ ($Casts.$to(item_8, MenuItem));
    goog.global.console.log('# Item ' + j_l_String.m_valueOf__java_lang_Object__java_lang_String(item_9.f_id__org_patternfly_component_menu_MenuItem) + ' clicked');
   })).m_description__java_lang_String__org_patternfly_component_menu_MenuItem('Description 2').m_addAction__org_patternfly_component_menu_MenuItemAction__org_patternfly_component_menu_MenuItem(MenuItemAction.m_menuItemAction__java_lang_String__org_patternfly_icon_PredefinedIcon__org_patternfly_component_menu_MenuItemAction('action-1', fas.m_clipboard__org_patternfly_icon_PredefinedIcon()).m_onClick__org_patternfly_handler_ComponentHandler__org_patternfly_component_menu_MenuItemAction(ComponentHandler.$adapt((/** Event */ e_10, itemAction_4) =>{
    let itemAction_5 = /**@type {MenuItemAction}*/ ($Casts.$to(itemAction_4, MenuItemAction));
    goog.global.console.log('# Action ' + j_l_String.m_valueOf__java_lang_Object__java_lang_String(itemAction_5.f_id__org_patternfly_component_menu_MenuItemAction) + ' on item ' + j_l_String.m_valueOf__java_lang_Object__java_lang_String(itemAction_5.f_menuItem__org_patternfly_component_menu_MenuItemAction.f_id__org_patternfly_component_menu_MenuItem) + ' clicked');
   })))).m_addItem__org_patternfly_component_menu_MenuItem__org_patternfly_component_menu_MenuList(MenuItem.m_actionMenuItem__java_lang_String__java_lang_String__org_patternfly_component_menu_MenuItem('item-2', 'Item 3').m_description__java_lang_String__org_patternfly_component_menu_MenuItem('Description 3').m_addAction__org_patternfly_component_menu_MenuItemAction__org_patternfly_component_menu_MenuItem(MenuItemAction.m_menuItemAction__java_lang_String__org_patternfly_icon_PredefinedIcon__org_patternfly_component_menu_MenuItemAction('action-2', patternfly.m_bell__org_patternfly_icon_PredefinedIcon()))))))), HTMLContainerBuilder)).m_element__elemental2_dom_HTMLElement(), HTMLDivElement_$Overlay));
  })));
  this.m_startApiDocs__java_lang_Class__void(Class.$get(Menu));
  this.m_addApiDoc__java_lang_Class__org_patternfly_showcase_ApiDoc_Type__void(Class.$get(Menu), Type.f_component__org_patternfly_showcase_ApiDoc_Type);
  this.m_addApiDoc__java_lang_Class__org_patternfly_showcase_ApiDoc_Type__void(Class.$get(MenuActionHandler), Type.f_handler__org_patternfly_showcase_ApiDoc_Type);
  this.m_addApiDoc__java_lang_Class__org_patternfly_showcase_ApiDoc_Type__void(Class.$get(MenuContent), Type.f_subcomponent__org_patternfly_showcase_ApiDoc_Type);
  this.m_addApiDoc__java_lang_Class__org_patternfly_showcase_ApiDoc_Type__void(Class.$get(MenuFooter), Type.f_subcomponent__org_patternfly_showcase_ApiDoc_Type);
  this.m_addApiDoc__java_lang_Class__org_patternfly_showcase_ApiDoc_Type__void(Class.$get(MenuGroup), Type.f_subcomponent__org_patternfly_showcase_ApiDoc_Type);
  this.m_addApiDoc__java_lang_Class__org_patternfly_showcase_ApiDoc_Type__void(Class.$get(MenuHeader), Type.f_subcomponent__org_patternfly_showcase_ApiDoc_Type);
  this.m_addApiDoc__java_lang_Class__org_patternfly_showcase_ApiDoc_Type__void(Class.$get(MenuItem), Type.f_subcomponent__org_patternfly_showcase_ApiDoc_Type);
  this.m_addApiDoc__java_lang_Class__org_patternfly_showcase_ApiDoc_Type__void(Class.$get(MenuItemAction), Type.f_subcomponent__org_patternfly_showcase_ApiDoc_Type);
  this.m_addApiDoc__java_lang_Class__org_patternfly_showcase_ApiDoc_Type__void(Class.$get(MenuItemType), Type.f_other__org_patternfly_showcase_ApiDoc_Type);
  this.m_addApiDoc__java_lang_Class__org_patternfly_showcase_ApiDoc_Type__void(Class.$get(MenuList), Type.f_subcomponent__org_patternfly_showcase_ApiDoc_Type);
  this.m_addApiDoc__java_lang_Class__org_patternfly_showcase_ApiDoc_Type__void(Class.$get(MenuSearch), Type.f_subcomponent__org_patternfly_showcase_ApiDoc_Type);
  this.m_addApiDoc__java_lang_Class__org_patternfly_showcase_ApiDoc_Type__void(Class.$get(MenuSearchInput), Type.f_subcomponent__org_patternfly_showcase_ApiDoc_Type);
  this.m_addApiDoc__java_lang_Class__org_patternfly_showcase_ApiDoc_Type__void(Class.$get(MenuType), Type.f_other__org_patternfly_showcase_ApiDoc_Type);
 }
 /** @nodts */
 static $clinit() {
  MenuComponent.$clinit = () =>{};
  MenuComponent.$loadModules();
  SnippetPage.$clinit();
 }
 /** @nodts @return {boolean} */
 static $isInstance(/** ? */ instance) {
  return instance instanceof MenuComponent;
 }
 
 /** @nodts */
 static $loadModules() {
  HTMLDivElement_$Overlay = goog.module.get('elemental2.dom.HTMLDivElement.$Overlay$impl');
  Class = goog.module.get('java.lang.Class$impl');
  j_l_String = goog.module.get('java.lang.String$impl');
  j_u_function_Function = goog.module.get('java.util.function.Function$impl');
  Supplier = goog.module.get('java.util.function.Supplier$impl');
  Collectors = goog.module.get('java.util.stream.Collectors$impl');
  $Overlay = goog.module.get('jsinterop.base.JsPropertyMap.$Overlay$impl');
  Elements = goog.module.get('org.jboss.elemento.Elements$impl');
  HTMLContainerBuilder = goog.module.get('org.jboss.elemento.HTMLContainerBuilder$impl');
  SelectionMode = goog.module.get('org.patternfly.component.SelectionMode$impl');
  Button = goog.module.get('org.patternfly.component.button.Button$impl');
  Menu = goog.module.get('org.patternfly.component.menu.Menu$impl');
  MenuActionHandler = goog.module.get('org.patternfly.component.menu.MenuActionHandler$impl');
  MenuContent = goog.module.get('org.patternfly.component.menu.MenuContent$impl');
  MenuFooter = goog.module.get('org.patternfly.component.menu.MenuFooter$impl');
  MenuGroup = goog.module.get('org.patternfly.component.menu.MenuGroup$impl');
  MenuHeader = goog.module.get('org.patternfly.component.menu.MenuHeader$impl');
  MenuItem = goog.module.get('org.patternfly.component.menu.MenuItem$impl');
  MenuItemAction = goog.module.get('org.patternfly.component.menu.MenuItemAction$impl');
  MenuItemType = goog.module.get('org.patternfly.component.menu.MenuItemType$impl');
  MenuList = goog.module.get('org.patternfly.component.menu.MenuList$impl');
  MenuSearch = goog.module.get('org.patternfly.component.menu.MenuSearch$impl');
  MenuSearchInput = goog.module.get('org.patternfly.component.menu.MenuSearchInput$impl');
  MenuType = goog.module.get('org.patternfly.component.menu.MenuType$impl');
  Aria = goog.module.get('org.patternfly.core.Aria$impl');
  ComponentHandler = goog.module.get('org.patternfly.handler.ComponentHandler$impl');
  MultiSelectHandler = goog.module.get('org.patternfly.handler.MultiSelectHandler$impl');
  SelectHandler = goog.module.get('org.patternfly.handler.SelectHandler$impl');
  fas = goog.module.get('org.patternfly.icon.IconSets.fas$impl');
  patternfly = goog.module.get('org.patternfly.icon.IconSets.patternfly$impl');
  Type = goog.module.get('org.patternfly.showcase.ApiDoc.Type$impl');
  Code = goog.module.get('org.patternfly.showcase.Code$impl');
  Data = goog.module.get('org.patternfly.showcase.Data$impl');
  LoremIpsum = goog.module.get('org.patternfly.showcase.LoremIpsum$impl');
  Snippet = goog.module.get('org.patternfly.showcase.Snippet$impl');
  Component_$Overlay = goog.module.get('org.patternfly.showcase.component.Component.$Overlay$impl');
  $Casts = goog.module.get('vmbootstrap.Casts$impl');
 }
}
$Util.$setClassMetadata(MenuComponent, 'org.patternfly.showcase.component.MenuComponent');

exports = MenuComponent;

//# sourceMappingURL=MenuComponent.js.map
