goog.module('org.patternfly.showcase.component.NavigationComponent');

goog.require('elemental2.dom.Event.$Overlay');
goog.require('elemental2.dom.HTMLDivElement.$Overlay');
goog.require('java.lang.Class');
goog.require('java.lang.Integer');
goog.require('java.lang.String');
goog.require('java.util.List');
goog.require('java.util.function.Function');
goog.require('java.util.function.Supplier');
goog.require('java.util.stream.Collector');
goog.require('java.util.stream.Collectors');
goog.require('java.util.stream.IntStream');
goog.require('jsinterop.base.JsPropertyMap.$Overlay');
goog.require('nativebootstrap.Util');
goog.require('org.jboss.elemento.Elements');
goog.require('org.jboss.elemento.HTMLContainerBuilder');
goog.require('org.patternfly.component.navigation.ExpandableNavigationGroup');
goog.require('org.patternfly.component.navigation.Navigation');
goog.require('org.patternfly.component.navigation.NavigationGroup');
goog.require('org.patternfly.component.navigation.NavigationItem');
goog.require('org.patternfly.component.navigation.NavigationLinkText');
goog.require('org.patternfly.component.navigation.NavigationType');
goog.require('org.patternfly.component.navigation.NavigationType.Horizontal');
goog.require('org.patternfly.component.navigation.NavigationType.Vertical');
goog.require('org.patternfly.handler.ComponentHandler');
goog.require('org.patternfly.icon.IconSets.fas');
goog.require('org.patternfly.showcase.ApiDoc.Type');
goog.require('org.patternfly.showcase.Code');
goog.require('org.patternfly.showcase.Data');
goog.require('org.patternfly.showcase.Snippet');
goog.require('org.patternfly.showcase.SnippetPage');
goog.require('org.patternfly.showcase.component.Component.$Overlay');
goog.require('org.patternfly.showcase.component.NotYetImplemented');
goog.require('vmbootstrap.Arrays');
goog.require('vmbootstrap.Casts');

const NavigationComponent = goog.require('org.patternfly.showcase.component.NavigationComponent$impl');
exports = NavigationComponent;
