goog.module('org.patternfly.showcase.component.ProgressComponent');

goog.require('elemental2.dom.Event.$Overlay');
goog.require('elemental2.dom.HTMLDivElement.$Overlay');
goog.require('java.lang.Boolean');
goog.require('java.lang.Class');
goog.require('java.lang.Integer');
goog.require('java.lang.String');
goog.require('java.util.function.Consumer');
goog.require('java.util.function.Supplier');
goog.require('jsinterop.base.JsPropertyMap.$Overlay');
goog.require('nativebootstrap.Equality');
goog.require('nativebootstrap.Util');
goog.require('org.jboss.elemento.Elements');
goog.require('org.jboss.elemento.HTMLContainerBuilder');
goog.require('org.jboss.elemento.Id');
goog.require('org.patternfly.component.form.Radio');
goog.require('org.patternfly.component.help.HelperText');
goog.require('org.patternfly.component.list.DescriptionList');
goog.require('org.patternfly.component.list.DescriptionListDescription');
goog.require('org.patternfly.component.list.DescriptionListGroup');
goog.require('org.patternfly.component.list.DescriptionListTerm');
goog.require('org.patternfly.component.progress.MeasureLocation');
goog.require('org.patternfly.component.progress.Progress');
goog.require('org.patternfly.component.progress.ProgressLabel');
goog.require('org.patternfly.core.Tuple');
goog.require('org.patternfly.core.Tuples');
goog.require('org.patternfly.handler.ChangeHandler');
goog.require('org.patternfly.showcase.ApiDoc.Type');
goog.require('org.patternfly.showcase.Code');
goog.require('org.patternfly.showcase.Data');
goog.require('org.patternfly.showcase.LoremIpsum');
goog.require('org.patternfly.showcase.Snippet');
goog.require('org.patternfly.showcase.SnippetPage');
goog.require('org.patternfly.showcase.component.Component.$Overlay');
goog.require('org.patternfly.style.Size');
goog.require('org.patternfly.style.Status');
goog.require('vmbootstrap.Arrays');
goog.require('vmbootstrap.Casts');

const ProgressComponent = goog.require('org.patternfly.showcase.component.ProgressComponent$impl');
exports = ProgressComponent;
