goog.module('org.patternfly.showcase.component.SliderComponent');

goog.require('elemental2.dom.DomGlobal.$Overlay');
goog.require('elemental2.dom.Event.$Overlay');
goog.require('elemental2.dom.HTMLDivElement.$Overlay');
goog.require('elemental2.dom.HTMLElement.$Overlay');
goog.require('elemental2.dom.HTMLParagraphElement.$Overlay');
goog.require('elemental2.dom.MouseEvent.$Overlay');
goog.require('java.lang.Class');
goog.require('java.lang.Double');
goog.require('java.lang.String');
goog.require('java.util.function.Supplier');
goog.require('jsinterop.base.JsPropertyMap.$Overlay');
goog.require('nativebootstrap.Util');
goog.require('org.jboss.elemento.Elements');
goog.require('org.jboss.elemento.EventType');
goog.require('org.jboss.elemento.HTMLContainerBuilder');
goog.require('org.jboss.elemento.Id');
goog.require('org.patternfly.component.button.Button');
goog.require('org.patternfly.component.form.TextInput');
goog.require('org.patternfly.component.form.TextInputType');
goog.require('org.patternfly.component.inputgroup.InputGroup');
goog.require('org.patternfly.component.inputgroup.InputGroupItem');
goog.require('org.patternfly.component.inputgroup.InputGroupText');
goog.require('org.patternfly.component.slider.Slider');
goog.require('org.patternfly.component.slider.SliderActions');
goog.require('org.patternfly.component.slider.SliderInputPosition');
goog.require('org.patternfly.component.slider.SliderStep');
goog.require('org.patternfly.component.slider.SliderSteps');
goog.require('org.patternfly.handler.ChangeHandler');
goog.require('org.patternfly.handler.ComponentHandler');
goog.require('org.patternfly.icon.IconSets.fas');
goog.require('org.patternfly.showcase.ApiDoc.Type');
goog.require('org.patternfly.showcase.Code');
goog.require('org.patternfly.showcase.Data');
goog.require('org.patternfly.showcase.Snippet');
goog.require('org.patternfly.showcase.SnippetPage');
goog.require('org.patternfly.showcase.component.Component.$Overlay');
goog.require('vmbootstrap.Arrays');
goog.require('vmbootstrap.Casts');

const SliderComponent = goog.require('org.patternfly.showcase.component.SliderComponent$impl');
exports = SliderComponent;
