goog.module('org.patternfly.showcase.component.TextAreaComponent');

goog.require('elemental2.dom.DomGlobal.$Overlay');
goog.require('elemental2.dom.Event.$Overlay');
goog.require('elemental2.dom.HTMLDivElement.$Overlay');
goog.require('java.lang.Boolean');
goog.require('java.lang.Class');
goog.require('java.lang.String');
goog.require('java.util.function.Supplier');
goog.require('jsinterop.base.JsPropertyMap.$Overlay');
goog.require('nativebootstrap.Util');
goog.require('org.jboss.elemento.Elements');
goog.require('org.jboss.elemento.HTMLContainerBuilder');
goog.require('org.patternfly.component.ValidationStatus');
goog.require('org.patternfly.component.form.Checkbox');
goog.require('org.patternfly.component.form.Form');
goog.require('org.patternfly.component.form.FormGroup');
goog.require('org.patternfly.component.form.FormGroupControl');
goog.require('org.patternfly.component.form.FormGroupLabel');
goog.require('org.patternfly.component.form.TextArea');
goog.require('org.patternfly.component.form.TextAreaResize');
goog.require('org.patternfly.component.help.HelperText');
goog.require('org.patternfly.handler.ChangeHandler');
goog.require('org.patternfly.showcase.ApiDoc.Type');
goog.require('org.patternfly.showcase.Code');
goog.require('org.patternfly.showcase.Data');
goog.require('org.patternfly.showcase.Snippet');
goog.require('org.patternfly.showcase.SnippetPage');
goog.require('org.patternfly.showcase.component.Component.$Overlay');
goog.require('org.patternfly.style.Classes');
goog.require('vmbootstrap.Arrays');
goog.require('vmbootstrap.Casts');
goog.require('vmbootstrap.primitives.$double');

const TextAreaComponent = goog.require('org.patternfly.showcase.component.TextAreaComponent$impl');
exports = TextAreaComponent;
