goog.module('org.patternfly.showcase.component.TextInputGroupComponent');

goog.require('elemental2.dom.Event.$Overlay');
goog.require('elemental2.dom.HTMLDivElement.$Overlay');
goog.require('elemental2.dom.MouseEvent.$Overlay');
goog.require('java.lang.Boolean');
goog.require('java.lang.Class');
goog.require('java.lang.String');
goog.require('java.util.Arrays');
goog.require('java.util.List');
goog.require('java.util.function.Function');
goog.require('java.util.function.Supplier');
goog.require('jsinterop.base.JsPropertyMap.$Overlay');
goog.require('nativebootstrap.Util');
goog.require('org.jboss.elemento.Elements');
goog.require('org.jboss.elemento.EventType');
goog.require('org.jboss.elemento.HTMLContainerBuilder');
goog.require('org.jboss.elemento.Key');
goog.require('org.patternfly.component.button.Button');
goog.require('org.patternfly.component.chip.Chip');
goog.require('org.patternfly.component.chip.ChipGroup');
goog.require('org.patternfly.component.textinputgroup.TextInputGroup');
goog.require('org.patternfly.component.textinputgroup.TextInputGroupMain');
goog.require('org.patternfly.component.textinputgroup.TextInputGroupUtilities');
goog.require('org.patternfly.core.ObservableValue');
goog.require('org.patternfly.core.ObservableValue.Subscriber');
goog.require('org.patternfly.handler.ChangeHandler');
goog.require('org.patternfly.handler.CloseHandler');
goog.require('org.patternfly.icon.IconSets.fas');
goog.require('org.patternfly.showcase.ApiDoc.Type');
goog.require('org.patternfly.showcase.Code');
goog.require('org.patternfly.showcase.Data');
goog.require('org.patternfly.showcase.Snippet');
goog.require('org.patternfly.showcase.SnippetPage');
goog.require('org.patternfly.showcase.component.Component.$Overlay');
goog.require('vmbootstrap.Arrays');
goog.require('vmbootstrap.Casts');

const TextInputGroupComponent = goog.require('org.patternfly.showcase.component.TextInputGroupComponent$impl');
exports = TextInputGroupComponent;
