goog.module('java.util.stream.Collectors');

goog.require('java.lang.CharSequence');
goog.require('java.lang.IllegalStateException');
goog.require('java.lang.Integer');
goog.require('java.lang.Long');
goog.require('java.lang.Object');
goog.require('java.lang.StringBuilder');
goog.require('java.util.ArrayList');
goog.require('java.util.Collection');
goog.require('java.util.Comparator');
goog.require('java.util.DoubleSummaryStatistics');
goog.require('java.util.HashMap');
goog.require('java.util.HashSet');
goog.require('java.util.IntSummaryStatistics');
goog.require('java.util.LinkedHashMap');
goog.require('java.util.List');
goog.require('java.util.LongSummaryStatistics');
goog.require('java.util.Map');
goog.require('java.util.Map.Entry');
goog.require('java.util.Optional');
goog.require('java.util.Set');
goog.require('java.util.StringJoiner');
goog.require('java.util.function.BiConsumer');
goog.require('java.util.function.BinaryOperator');
goog.require('java.util.function.Function');
goog.require('java.util.function.Predicate');
goog.require('java.util.function.Supplier');
goog.require('java.util.function.ToDoubleFunction');
goog.require('java.util.function.ToIntFunction');
goog.require('java.util.function.ToLongFunction');
goog.require('java.util.stream.Collector');
goog.require('java.util.stream.Collector.Characteristics');
goog.require('java.util.stream.CollectorImpl');
goog.require('nativebootstrap.Equality');
goog.require('nativebootstrap.Long');
goog.require('nativebootstrap.Util');
goog.require('vmbootstrap.Arrays');
goog.require('vmbootstrap.Casts');
goog.require('vmbootstrap.Exceptions');
goog.require('vmbootstrap.LongUtils');
goog.require('vmbootstrap.Primitives');

const Collectors = goog.require('java.util.stream.Collectors$impl');
exports = Collectors;
