goog.module('java.util.stream.DoubleStream');

goog.require('java.lang.Long');
goog.require('java.lang.Runnable');
goog.require('java.util.Arrays');
goog.require('java.util.DoubleSummaryStatistics');
goog.require('java.util.List');
goog.require('java.util.OptionalDouble');
goog.require('java.util.PrimitiveIterator.OfDouble');
goog.require('java.util.Spliterator');
goog.require('java.util.Spliterator.OfDouble');
goog.require('java.util.function.BiConsumer');
goog.require('java.util.function.DoubleBinaryOperator');
goog.require('java.util.function.DoubleConsumer');
goog.require('java.util.function.DoubleFunction');
goog.require('java.util.function.DoublePredicate');
goog.require('java.util.function.DoubleSupplier');
goog.require('java.util.function.DoubleToIntFunction');
goog.require('java.util.function.DoubleToLongFunction');
goog.require('java.util.function.DoubleUnaryOperator');
goog.require('java.util.function.ObjDoubleConsumer');
goog.require('java.util.function.Supplier');
goog.require('java.util.stream.BaseStream');
goog.require('java.util.stream.DoubleStream.$1');
goog.require('java.util.stream.DoubleStream.$2');
goog.require('java.util.stream.DoubleStream.$3');
goog.require('java.util.stream.DoubleStream.$4');
goog.require('java.util.stream.DoubleStream.Builder');
goog.require('java.util.stream.DoubleStreamImpl');
goog.require('java.util.stream.DoubleStreamImpl.Empty');
goog.require('java.util.stream.IntStream');
goog.require('java.util.stream.LongStream');
goog.require('java.util.stream.Stream');
goog.require('java.util.stream.StreamSupport');
goog.require('nativebootstrap.Long');
goog.require('nativebootstrap.Util');
goog.require('vmbootstrap.Arrays');
goog.require('vmbootstrap.Casts');
goog.require('vmbootstrap.primitives.$double');

const DoubleStream = goog.require('java.util.stream.DoubleStream$impl');
exports = DoubleStream;
