goog.module('java.util.stream.IntStreamImpl.Empty');

goog.require('java.lang.Integer');
goog.require('java.lang.Runnable');
goog.require('java.util.IntSummaryStatistics');
goog.require('java.util.OptionalDouble');
goog.require('java.util.OptionalInt');
goog.require('java.util.PrimitiveIterator.OfInt');
goog.require('java.util.Spliterator.OfInt');
goog.require('java.util.Spliterators');
goog.require('java.util.function.BiConsumer');
goog.require('java.util.function.IntBinaryOperator');
goog.require('java.util.function.IntConsumer');
goog.require('java.util.function.IntFunction');
goog.require('java.util.function.IntPredicate');
goog.require('java.util.function.IntToDoubleFunction');
goog.require('java.util.function.IntToLongFunction');
goog.require('java.util.function.IntUnaryOperator');
goog.require('java.util.function.ObjIntConsumer');
goog.require('java.util.function.Supplier');
goog.require('java.util.stream.DoubleStream');
goog.require('java.util.stream.DoubleStreamImpl.Empty');
goog.require('java.util.stream.IntStream');
goog.require('java.util.stream.LongStream');
goog.require('java.util.stream.LongStreamImpl.Empty');
goog.require('java.util.stream.Stream');
goog.require('java.util.stream.StreamImpl.Empty');
goog.require('java.util.stream.TerminatableStream');
goog.require('javaemul.internal.InternalPreconditions');
goog.require('nativebootstrap.Long');
goog.require('nativebootstrap.Util');
goog.require('vmbootstrap.Arrays');
goog.require('vmbootstrap.Casts');
goog.require('vmbootstrap.LongUtils');
goog.require('vmbootstrap.primitives.$int');

const Empty = goog.require('java.util.stream.IntStreamImpl.Empty$impl');
exports = Empty;
