goog.module('java.util.stream.LongStreamImpl.Empty');

goog.require('java.lang.Long');
goog.require('java.lang.Runnable');
goog.require('java.util.LongSummaryStatistics');
goog.require('java.util.OptionalDouble');
goog.require('java.util.OptionalLong');
goog.require('java.util.PrimitiveIterator.OfLong');
goog.require('java.util.Spliterator.OfLong');
goog.require('java.util.Spliterators');
goog.require('java.util.function.BiConsumer');
goog.require('java.util.function.LongBinaryOperator');
goog.require('java.util.function.LongConsumer');
goog.require('java.util.function.LongFunction');
goog.require('java.util.function.LongPredicate');
goog.require('java.util.function.LongToDoubleFunction');
goog.require('java.util.function.LongToIntFunction');
goog.require('java.util.function.LongUnaryOperator');
goog.require('java.util.function.ObjLongConsumer');
goog.require('java.util.function.Supplier');
goog.require('java.util.stream.DoubleStream');
goog.require('java.util.stream.DoubleStreamImpl.Empty');
goog.require('java.util.stream.IntStream');
goog.require('java.util.stream.IntStreamImpl.Empty');
goog.require('java.util.stream.LongStream');
goog.require('java.util.stream.Stream');
goog.require('java.util.stream.StreamImpl.Empty');
goog.require('java.util.stream.TerminatableStream');
goog.require('javaemul.internal.InternalPreconditions');
goog.require('nativebootstrap.Long');
goog.require('nativebootstrap.Util');
goog.require('vmbootstrap.Arrays');
goog.require('vmbootstrap.Casts');
goog.require('vmbootstrap.LongUtils');
goog.require('vmbootstrap.primitives.$long');

const Empty = goog.require('java.util.stream.LongStreamImpl.Empty$impl');
exports = Empty;
