goog.module('java.util.stream.StreamImpl.Empty');

goog.require('java.lang.Object');
goog.require('java.lang.Runnable');
goog.require('java.util.Collections');
goog.require('java.util.Comparator');
goog.require('java.util.Iterator');
goog.require('java.util.Optional');
goog.require('java.util.Spliterator');
goog.require('java.util.Spliterators');
goog.require('java.util.function.BiConsumer');
goog.require('java.util.function.BiFunction');
goog.require('java.util.function.BinaryOperator');
goog.require('java.util.function.Consumer');
goog.require('java.util.function.Function');
goog.require('java.util.function.IntFunction');
goog.require('java.util.function.Predicate');
goog.require('java.util.function.Supplier');
goog.require('java.util.function.ToDoubleFunction');
goog.require('java.util.function.ToIntFunction');
goog.require('java.util.function.ToLongFunction');
goog.require('java.util.stream.Collector');
goog.require('java.util.stream.DoubleStream');
goog.require('java.util.stream.DoubleStreamImpl.Empty');
goog.require('java.util.stream.IntStream');
goog.require('java.util.stream.IntStreamImpl.Empty');
goog.require('java.util.stream.LongStream');
goog.require('java.util.stream.LongStreamImpl.Empty');
goog.require('java.util.stream.Stream');
goog.require('java.util.stream.TerminatableStream');
goog.require('javaemul.internal.InternalPreconditions');
goog.require('nativebootstrap.Long');
goog.require('nativebootstrap.Util');
goog.require('vmbootstrap.Arrays');
goog.require('vmbootstrap.Casts');
goog.require('vmbootstrap.LongUtils');

const Empty = goog.require('java.util.stream.StreamImpl.Empty$impl');
exports = Empty;
