goog.module('org.patternfly.showcase.Showcase');

goog.require('java.lang.Object');
goog.require('java.lang.String');
goog.require('java.util.function.Function');
goog.require('nativebootstrap.Util');
goog.require('org.jboss.elemento.By');
goog.require('org.jboss.elemento.Elements');
goog.require('org.jboss.elemento.router.AfterPlaceHandler');
goog.require('org.jboss.elemento.router.Page');
goog.require('org.jboss.elemento.router.Place');
goog.require('org.jboss.elemento.router.PlaceManager');
goog.require('org.jboss.elemento.router.RoutesImpl');
goog.require('org.patternfly.component.backtotop.BackToTop');
goog.require('org.patternfly.component.brand.Brand');
goog.require('org.patternfly.component.navigation.ExpandableNavigationGroup');
goog.require('org.patternfly.component.navigation.Navigation');
goog.require('org.patternfly.component.navigation.NavigationItem');
goog.require('org.patternfly.component.navigation.NavigationType.Vertical');
goog.require('org.patternfly.component.page.Masthead');
goog.require('org.patternfly.component.page.MastheadBrand');
goog.require('org.patternfly.component.page.MastheadMain');
goog.require('org.patternfly.component.page.MastheadToggle');
goog.require('org.patternfly.component.page.Page');
goog.require('org.patternfly.component.page.PageMain');
goog.require('org.patternfly.component.page.PageSidebar');
goog.require('org.patternfly.component.page.PageSidebarBody');
goog.require('org.patternfly.component.skiptocontent.SkipToContent');
goog.require('org.patternfly.showcase.ApiDoc');
goog.require('org.patternfly.showcase.Assets');
goog.require('org.patternfly.showcase.Data');
goog.require('org.patternfly.showcase.NotFound');
goog.require('org.patternfly.showcase.component.Component.$Overlay');
goog.require('org.patternfly.showcase.layout.Layout.$Overlay');
goog.require('org.patternfly.style.Classes');
goog.require('org.patternfly.style.Variable');
goog.require('org.patternfly.style.Variables');
goog.require('vmbootstrap.Arrays');
goog.require('vmbootstrap.Casts');

const Showcase = goog.require('org.patternfly.showcase.Showcase$impl');
exports = Showcase;
