goog.module('org.patternfly.showcase.Snippet');

goog.require('elemental2.dom.Event.$Overlay');
goog.require('elemental2.dom.HTMLAnchorElement.$Overlay');
goog.require('elemental2.dom.HTMLDivElement.$Overlay');
goog.require('elemental2.dom.HTMLElement.$Overlay');
goog.require('elemental2.dom.HTMLParagraphElement.$Overlay');
goog.require('java.lang.Object');
goog.require('java.lang.String');
goog.require('java.util.function.Consumer');
goog.require('java.util.function.Supplier');
goog.require('nativebootstrap.Equality');
goog.require('nativebootstrap.Util');
goog.require('org.jboss.elemento.By');
goog.require('org.jboss.elemento.Elements');
goog.require('org.jboss.elemento.HTMLContainerBuilder');
goog.require('org.jboss.elemento.HTMLElementBuilder');
goog.require('org.jboss.elemento.Id');
goog.require('org.jboss.elemento.IsElement');
goog.require('org.patternfly.component.button.Button');
goog.require('org.patternfly.component.code.CodeEditor');
goog.require('org.patternfly.component.code.CodeEditorAction');
goog.require('org.patternfly.component.code.CodeEditorActions');
goog.require('org.patternfly.component.code.CodeEditorHeader');
goog.require('org.patternfly.component.title.Title');
goog.require('org.patternfly.component.tooltip.Tooltip');
goog.require('org.patternfly.core.Aria');
goog.require('org.patternfly.core.Attributes');
goog.require('org.patternfly.handler.ComponentHandler');
goog.require('org.patternfly.icon.IconSets.fas');
goog.require('org.patternfly.layout.flex.AlignItems');
goog.require('org.patternfly.layout.flex.Flex');
goog.require('org.patternfly.layout.flex.SpaceItems');
goog.require('org.patternfly.showcase.LinkIcon');
goog.require('org.patternfly.style.Breakpoint');
goog.require('org.patternfly.style.Breakpoints');
goog.require('org.patternfly.style.Classes');
goog.require('org.patternfly.style.Size');
goog.require('vmbootstrap.Arrays');
goog.require('vmbootstrap.Casts');

const Snippet = goog.require('org.patternfly.showcase.Snippet$impl');
exports = Snippet;
