goog.module('java.math.BigInteger');

goog.require('java.io.Serializable');
goog.require('java.lang.ArithmeticException');
goog.require('java.lang.Byte');
goog.require('java.lang.Character');
goog.require('java.lang.Comparable');
goog.require('java.lang.Double');
goog.require('java.lang.Float');
goog.require('java.lang.Integer');
goog.require('java.lang.Long');
goog.require('java.lang.Number');
goog.require('java.lang.NumberFormatException');
goog.require('java.lang.Short');
goog.require('java.lang.String');
goog.require('java.lang.System');
goog.require('java.math.BitLevel');
goog.require('java.math.Conversion');
goog.require('java.math.Division');
goog.require('java.math.Elementary');
goog.require('java.math.Logical');
goog.require('java.math.Multiplication');
goog.require('java.math.Primality');
goog.require('java.util.Random');
goog.require('javaemul.internal.InternalPreconditions');
goog.require('nativebootstrap.Equality');
goog.require('nativebootstrap.Long');
goog.require('nativebootstrap.Util');
goog.require('vmbootstrap.Arrays');
goog.require('vmbootstrap.Casts');
goog.require('vmbootstrap.Exceptions');
goog.require('vmbootstrap.LongUtils');
goog.require('vmbootstrap.Primitives');
goog.require('vmbootstrap.primitives.$byte');
goog.require('vmbootstrap.primitives.$int');

const BigInteger = goog.require('java.math.BigInteger$impl');
exports = BigInteger;
