ignoredBuiltDependencies:
  - '@swc/core'
  - lmdb
  - msgpackr-extract
  - puppeteer

onlyBuiltDependencies:
  - '@parcel/watcher'

overrides:
  axios@>=1.0.0 <1.15.1: '>=1.15.1'
  axios@>=1.0.0 <1.15.2: '>=1.15.2'
  basic-ftp@<=5.2.2: '>=5.3.0'
  basic-ftp@<=5.3.0: '>=5.3.1'
  follow-redirects@<=1.15.11: '>=1.16.0'
  ip-address@<=10.1.0: '>=10.1.1'
