goog.module('org.patternfly.showcase.layout.LayoutsPage');

goog.require('elemental2.dom.HTMLAnchorElement.$Overlay');
goog.require('elemental2.dom.HTMLDivElement.$Overlay');
goog.require('elemental2.dom.HTMLParagraphElement.$Overlay');
goog.require('java.lang.String');
goog.require('java.util.function.Function');
goog.require('nativebootstrap.Util');
goog.require('org.jboss.elemento.Elements');
goog.require('org.jboss.elemento.HTMLContainerBuilder');
goog.require('org.jboss.elemento.router.Page');
goog.require('org.patternfly.component.card.Card');
goog.require('org.patternfly.component.card.CardBody');
goog.require('org.patternfly.component.card.CardTitle');
goog.require('org.patternfly.component.text.TextContent');
goog.require('org.patternfly.component.title.Title');
goog.require('org.patternfly.layout.flex.AlignItems');
goog.require('org.patternfly.layout.flex.Flex');
goog.require('org.patternfly.layout.flex.SpaceItems');
goog.require('org.patternfly.layout.gallery.Gallery');
goog.require('org.patternfly.layout.gallery.GalleryItem');
goog.require('org.patternfly.showcase.Data');
goog.require('org.patternfly.showcase.OverviewPage');
goog.require('org.patternfly.showcase.layout.Layout.$Overlay');
goog.require('org.patternfly.style.Breakpoint');
goog.require('org.patternfly.style.Breakpoints');
goog.require('org.patternfly.style.Classes');
goog.require('org.patternfly.style.Size');
goog.require('vmbootstrap.Arrays');
goog.require('vmbootstrap.Casts');

const LayoutsPage = goog.require('org.patternfly.showcase.layout.LayoutsPage$impl');
exports = LayoutsPage;
