goog.module('org.patternfly.component.code.CodeBlockAction');

goog.require('elemental2.dom.Element.$Overlay');
goog.require('elemental2.dom.Event.$Overlay');
goog.require('elemental2.dom.HTMLDivElement.$Overlay');
goog.require('elemental2.dom.MouseEvent.$Overlay');
goog.require('java.lang.String');
goog.require('nativebootstrap.Util');
goog.require('org.jboss.elemento.By');
goog.require('org.jboss.elemento.DomGlobal.$Overlay');
goog.require('org.jboss.elemento.Elements');
goog.require('org.jboss.elemento.EventType');
goog.require('org.jboss.elemento.HTMLContainerBuilder');
goog.require('org.jboss.elemento.Id');
goog.require('org.patternfly.component.ComponentType');
goog.require('org.patternfly.component.WithIcon');
goog.require('org.patternfly.component.button.Button');
goog.require('org.patternfly.component.code.CodeBlock');
goog.require('org.patternfly.component.code.CodeBlockSubComponent');
goog.require('org.patternfly.component.tooltip.Tooltip');
goog.require('org.patternfly.core.Aria');
goog.require('org.patternfly.handler.CloseHandler');
goog.require('org.patternfly.handler.ComponentHandler');
goog.require('org.patternfly.icon.IconSets.fas');
goog.require('org.patternfly.icon.PredefinedIcon');
goog.require('org.patternfly.style.Classes');
goog.require('vmbootstrap.Arrays');
goog.require('vmbootstrap.Casts');

const CodeBlockAction = goog.require('org.patternfly.component.code.CodeBlockAction$impl');
exports = CodeBlockAction;
