goog.module('org.jboss.elemento.router.PlaceManager');

goog.require('elemental2.dom.DomGlobal.$Overlay');
goog.require('elemental2.dom.Element.$Overlay');
goog.require('elemental2.dom.Event.$Overlay');
goog.require('elemental2.dom.HTMLAnchorElement.$Overlay');
goog.require('elemental2.dom.HTMLElement.$Overlay');
goog.require('elemental2.dom.History.$Overlay');
goog.require('elemental2.dom.MouseEvent.$Overlay');
goog.require('elemental2.dom.PopStateEvent.$Overlay');
goog.require('elemental2.dom.URL.$Overlay');
goog.require('java.lang.Object');
goog.require('java.lang.String');
goog.require('java.util.ArrayList');
goog.require('java.util.HashMap');
goog.require('java.util.List');
goog.require('java.util.Map');
goog.require('java.util.Map.Entry');
goog.require('java.util.function.Function');
goog.require('java.util.function.Supplier');
goog.require('nativebootstrap.Equality');
goog.require('nativebootstrap.Util');
goog.require('org.jboss.elemento.By');
goog.require('org.jboss.elemento.Elements');
goog.require('org.jboss.elemento.EventType');
goog.require('org.jboss.elemento.router.AfterPlaceHandler');
goog.require('org.jboss.elemento.router.Base');
goog.require('org.jboss.elemento.router.BeforePlaceHandler');
goog.require('org.jboss.elemento.router.LinkSelector');
goog.require('org.jboss.elemento.router.Page');
goog.require('org.jboss.elemento.router.Place');
goog.require('org.jboss.elemento.router.PlaceManager.DefaultNotFound');
goog.require('vmbootstrap.Casts');

const PlaceManager = goog.require('org.jboss.elemento.router.PlaceManager$impl');
exports = PlaceManager;
