goog.module('org.patternfly.component.alert.Alert');

goog.require('elemental2.dom.DomGlobal.$Overlay');
goog.require('elemental2.dom.Element.$Overlay');
goog.require('elemental2.dom.Event.$Overlay');
goog.require('elemental2.dom.HTMLDivElement.$Overlay');
goog.require('elemental2.dom.HTMLElement.$Overlay');
goog.require('elemental2.dom.HTMLParagraphElement.$Overlay');
goog.require('elemental2.dom.MouseEvent.$Overlay');
goog.require('elemental2.dom.MutationRecord.$Overlay');
goog.require('java.lang.String');
goog.require('nativebootstrap.Equality');
goog.require('nativebootstrap.Util');
goog.require('org.jboss.elemento.Attachable');
goog.require('org.jboss.elemento.Elements');
goog.require('org.jboss.elemento.EventType');
goog.require('org.jboss.elemento.HTMLContainerBuilder');
goog.require('org.patternfly.component.BaseComponent');
goog.require('org.patternfly.component.Closeable');
goog.require('org.patternfly.component.ComponentType');
goog.require('org.patternfly.component.Expandable');
goog.require('org.patternfly.component.Severity');
goog.require('org.patternfly.component.WithIcon');
goog.require('org.patternfly.component.alert.AlertActionGroup');
goog.require('org.patternfly.component.alert.AlertDescription');
goog.require('org.patternfly.component.alert.AlertGroup');
goog.require('org.patternfly.component.button.Button');
goog.require('org.patternfly.core.Aria');
goog.require('org.patternfly.core.Logger');
goog.require('org.patternfly.handler.CloseHandler');
goog.require('org.patternfly.handler.ToggleHandler');
goog.require('org.patternfly.icon.IconSets.fas');
goog.require('org.patternfly.icon.PredefinedIcon');
goog.require('org.patternfly.style.Classes');
goog.require('org.patternfly.style.Modifiers.Inline');
goog.require('org.patternfly.style.Modifiers.Plain');
goog.require('org.patternfly.style.Variable');
goog.require('vmbootstrap.Arrays');
goog.require('vmbootstrap.Casts');

const Alert = goog.require('org.patternfly.component.alert.Alert$impl');
exports = Alert;
