goog.module('org.patternfly.component.form.TextArea');

goog.require('elemental2.dom.Element.$Overlay');
goog.require('elemental2.dom.Event.$Overlay');
goog.require('elemental2.dom.EventListener.$Overlay');
goog.require('elemental2.dom.HTMLElement.$Overlay');
goog.require('elemental2.dom.HTMLTextAreaElement.$Overlay');
goog.require('elemental2.dom.MutationRecord.$Overlay');
goog.require('java.lang.Integer');
goog.require('java.lang.String');
goog.require('java.util.Objects');
goog.require('java.util.function.Consumer');
goog.require('nativebootstrap.Equality');
goog.require('nativebootstrap.Util');
goog.require('org.jboss.elemento.Attachable');
goog.require('org.jboss.elemento.DomGlobal.$Overlay');
goog.require('org.jboss.elemento.Elements');
goog.require('org.jboss.elemento.EventType');
goog.require('org.jboss.elemento.HTMLContainerBuilder');
goog.require('org.jboss.elemento.HTMLElementBuilder');
goog.require('org.patternfly.component.ComponentType');
goog.require('org.patternfly.component.HasValue');
goog.require('org.patternfly.component.WithText');
goog.require('org.patternfly.component.form.FormControl');
goog.require('org.patternfly.component.form.TextAreaResize');
goog.require('org.patternfly.core.Aria');
goog.require('org.patternfly.core.Attributes');
goog.require('org.patternfly.handler.ChangeHandler');
goog.require('org.patternfly.style.Modifiers.Plain');
goog.require('org.patternfly.style.Modifiers.Readonly');
goog.require('vmbootstrap.Arrays');
goog.require('vmbootstrap.Casts');

const TextArea = goog.require('org.patternfly.component.form.TextArea$impl');
exports = TextArea;
