name: Release PatternFly Java

on:
  push:
    tags:
      - 'v*'

jobs:
  deploy:
    name: Deploy Maven Artifacts
    runs-on: ubuntu-latest
    env:
      MVN: ./mvnw --show-version --batch-mode --no-transfer-progress
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: temurin
          cache: maven
      - run: $MVN package
      - uses: actions/setup-java@v4
        with: # running setup-java again overwrites the settings.xml
          java-version: 17
          distribution: temurin
          server-id: ossrh
          server-username: OSSRH_USERNAME
          server-password: OSSRH_PASSWORD
          gpg-private-key: ${{ secrets.MAVEN_GPG_PRIVATE_KEY }}
          gpg-passphrase: MAVEN_GPG_PASSPHRASE
      - run: $MVN deploy -P release
        env:
          OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
          MAVEN_GPG_PASSPHRASE: ${{ secrets.MAVEN_GPG_PASSPHRASE }}

  publish-apidocs:
    name: Publish API Documentation
    runs-on: ubuntu-latest
    env:
      MVN: ./mvnw --show-version --batch-mode --no-transfer-progress
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: temurin
          cache: maven
      - run: |
          $MVN -D quickly clean install
          $MVN -P snippets javadoc:aggregate
          $MVN -P snippets javadoc:javadoc
          $MVN -P snippets org.apache.maven.plugins:maven-antrun-plugin:run@copy-apidocs
      - uses: JamesIves/github-pages-deploy-action@v4.6.3
        with:
          token: ${{ secrets.PUBLISH_CONTENT }}
          repository-name: patternfly-java/apidocs
          branch: main
          folder: ./target/site/apidocs
          clean: true

  publish-showcase:
    name: Publish Showcase
    runs-on: ubuntu-latest
    env:
      MVN: ./mvnw --show-version --batch-mode --no-transfer-progress
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: temurin
          cache: maven
      - run: $MVN --projects org.patternfly:patternfly-java-showcase-j2cl --also-make -P showcase,prod package
      - uses: JamesIves/github-pages-deploy-action@v4.6.3
        with:
          token: ${{ secrets.PUBLISH_CONTENT }}
          repository-name: patternfly-java/patternfly-java.github.io
          branch: main
          folder: ./showcase/j2cl/target/showcase
          clean: true

  release:
    name: Create GitHub Release
    needs: deploy
    runs-on: ubuntu-latest
    steps:
      - name: Get Version
        id: get-version
        uses: battila7/get-version-action@v2.3.0
      - uses: actions/checkout@v4
      - name: Read Changelog
        id: read-changelog
        uses: mindsers/changelog-reader-action@v2
        with:
          path: ./CHANGELOG.md
          version: ${{ steps.get-version.outputs.version-without-v }}
      - uses: softprops/action-gh-release@v2.0.7
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.get-version.outputs.version }}
          name: PatternFly Java ${{ steps.get-version.outputs.version-without-v }}
          body: ${{ steps.read-changelog.outputs.changes }}
          draft: false
          prerelease: false
          discussion_category_name: announcements
